/**
 * Coach tips catalog — 45 hand-written tips across 7 categories.
 * Each tip is leveled (beginner/intermediate/advanced) and time-gated (weeks 1-12).
 * Tips are never repeated for a user — tracked via user_prefs.coachTipHistory.sentIds.
 */

const CATALOG = [
  // ─── PROGRESS (Where you are on the journey) ──────────────────────────────
  {
    id: 'tip_progress_1w',
    category: 'progress',
    levels: ['beginner', 'intermediate'],
    weekRange: { min: 1, max: 2 },
    body: 'You\'re one week in — this is when riding stops feeling like effort and starts feeling like something you actually want to do. The fact you\'re still here is the hard bit, the rest is downhill.',
  },
  {
    id: 'tip_progress_3w',
    category: 'progress',
    levels: ['beginner'],
    weekRange: { min: 3, max: 4 },
    body: 'Three weeks in — right about now most riders find their rhythm. Your legs stop complaining on climbs. Your breathing settles. You realise you\'re stronger than you thought.',
  },
  {
    id: 'tip_progress_5w',
    category: 'progress',
    levels: ['beginner', 'intermediate'],
    weekRange: { min: 5, max: 6 },
    body: 'Halfway through and you\'re building a real habit. Notice how riding doesn\'t feel scary anymore? That\'s exactly what\'s supposed to happen. You\'re not fit yet — you\'re just comfortable.',
  },
  {
    id: 'tip_progress_8w',
    category: 'progress',
    levels: ['beginner'],
    weekRange: { min: 8, max: 10 },
    body: 'Eight weeks in — the fitness is coming. You\'ll notice it on climbs and on longer rides. But the biggest win? You\'re doing this regularly now. The habit is locked in.',
  },
  {
    id: 'tip_progress_endgame',
    category: 'progress',
    levels: ['beginner', 'intermediate'],
    weekRange: { min: 10, max: 12 },
    body: 'Final weeks — you\'ve earned this. Look at what you can do now that you couldn\'t 12 weeks ago. The next step is picking another goal, or just riding for the joy of it.',
  },
  {
    id: 'tip_progress_comparison',
    category: 'progress',
    levels: ['beginner'],
    weekRange: null,
    body: 'Don\'t compare your week 3 to someone else\'s week 8. Everyone builds fitness at their own pace. Your only comparison is last week\'s you.',
  },

  // ─── BODY (What's happening positively to your body) ──────────────────────
  {
    id: 'tip_body_hrv',
    category: 'body',
    levels: ['beginner', 'intermediate'],
    weekRange: { min: 2, max: 6 },
    body: 'You might notice your resting heart rate dropping over the next few weeks — that\'s your aerobic system actually getting better at its job, not just feeling fitter.',
  },
  {
    id: 'tip_body_sleep',
    category: 'body',
    levels: ['beginner'],
    weekRange: null,
    body: 'Have you noticed you\'re sleeping better? Regular cycling quiets your nervous system. That\'s not a side-effect — that\'s the magic.',
  },
  {
    id: 'tip_body_stress',
    category: 'body',
    levels: ['beginner', 'intermediate', 'advanced'],
    weekRange: null,
    body: 'Most cyclists realise after a few weeks that riding is better than coffee for clearing your head. Use it that way.',
  },
  {
    id: 'tip_body_breathing',
    category: 'body',
    levels: ['beginner'],
    weekRange: { min: 4, max: 8 },
    body: 'Your breathing should be settling down on easy rides by now. If the first 10 minutes still feel breathless, slow down — there\'s no race.',
  },
  {
    id: 'tip_body_energy',
    category: 'body',
    levels: ['beginner'],
    weekRange: { min: 5, max: 12 },
    body: 'Feel more energetic off the bike? That\'s your aerobic system improving. The training is working.',
  },
  {
    id: 'tip_body_legs',
    category: 'body',
    levels: ['beginner', 'intermediate'],
    weekRange: { min: 6, max: 10 },
    body: 'Hills are getting easier, even if they don\'t feel easy. You\'re adapting. Keep going.',
  },

  // ─── GEAR (Things to start thinking about) ──────────────────────────────────
  {
    id: 'tip_gear_cleats',
    category: 'gear',
    levels: ['beginner'],
    weekRange: { min: 3, max: 8 },
    body: 'Around now most riders wonder about clipless pedals. They\'re not essential, but they make every ride feel more connected to the bike. No rush — when your current setup feels limiting, that\'s the signal.',
  },
  {
    id: 'tip_gear_shorts',
    category: 'gear',
    levels: ['beginner'],
    weekRange: null,
    body: 'Good padded cycling shorts aren\'t a luxury — they\'re load management. If you\'re on a budget, one good pair works fine.',
  },
  {
    id: 'tip_gear_lights',
    category: 'gear',
    levels: ['beginner', 'intermediate', 'advanced'],
    weekRange: null,
    body: 'If you\'re riding early or late, lights matter more than you think. Even in daylight, they help drivers spot you.',
  },
  {
    id: 'tip_gear_maintenance',
    category: 'gear',
    levels: ['beginner'],
    weekRange: { min: 4, max: 8 },
    body: 'Learn to fix a flat and do a basic chain clean. It\'s not scary, and it saves you a 45-minute walk home.',
  },
  {
    id: 'tip_gear_computer',
    category: 'gear',
    levels: ['beginner', 'intermediate'],
    weekRange: { min: 6, max: 12 },
    body: 'A bike computer is nice, but Strava on your phone does the job. You don\'t need a power meter or a fancy head unit.',
  },

  // ─── CULTURE (YouTube channels / races to watch) ──────────────────────────
  {
    id: 'tip_culture_tour',
    category: 'culture',
    levels: ['beginner', 'intermediate', 'advanced'],
    weekRange: null,
    body: 'If you\'ve never watched highlights from the Tour de France, give them a go on YouTube. It\'s surprisingly emotional once you\'ve done some cycling yourself — you understand what they\'re going through.',
  },
  {
    id: 'tip_culture_gcn',
    category: 'culture',
    levels: ['beginner'],
    weekRange: null,
    body: 'Global Cycling Network on YouTube has great tips that don\'t take themselves too seriously. Mix of technique, gear, and motivation.',
  },
  {
    id: 'tip_culture_giro',
    category: 'culture',
    levels: ['beginner', 'intermediate', 'advanced'],
    weekRange: null,
    body: 'The Giro d\'Italia is even more dramatic than the Tour. If you like scenery, mountains, and chaos, watch the highlights.',
  },
  {
    id: 'tip_culture_vuelta',
    category: 'culture',
    levels: ['intermediate', 'advanced'],
    weekRange: null,
    body: 'The Vuelta is the underdog Grand Tour. Less hyped than the Tour, but the riding is incredible.',
  },
  {
    id: 'tip_culture_cyclocross',
    category: 'culture',
    levels: ['beginner', 'intermediate'],
    weekRange: null,
    body: 'Ever seen cyclocross? It\'s basically running and riding mixed together, and it\'s wild. Autumn weekends on YouTube.',
  },

  // ─── NUTRITION (Have you tried eating more of...) ───────────────────────────
  {
    id: 'tip_nutrition_long',
    category: 'nutrition',
    levels: ['beginner', 'intermediate', 'advanced'],
    weekRange: null,
    body: 'If you\'re riding more than 90 minutes, eat something on the bike — a banana, a flapjack, a gel. Most beginners under-eat and wonder why the second hour feels rough.',
  },
  {
    id: 'tip_nutrition_carbs',
    category: 'nutrition',
    levels: ['beginner', 'intermediate'],
    weekRange: { min: 5, max: 12 },
    body: 'More training means you need more carbs, not less. Toast, pasta, rice. Your body is working harder and needs fuel.',
  },
  {
    id: 'tip_nutrition_protein',
    category: 'nutrition',
    levels: ['beginner', 'intermediate', 'advanced'],
    weekRange: null,
    body: 'Aim for protein within 30 minutes of finishing a ride — a smoothie, some yogurt, a sandwich. Helps recovery.',
  },
  {
    id: 'tip_nutrition_hydration',
    category: 'nutrition',
    levels: ['beginner', 'intermediate', 'advanced'],
    weekRange: null,
    body: 'Drink before you\'re thirsty. By the time thirst kicks in, you\'re already losing performance. One bottle per hour is a good baseline.',
  },
  {
    id: 'tip_nutrition_breakfast',
    category: 'nutrition',
    levels: ['beginner'],
    weekRange: null,
    body: 'Eat something light 1–2 hours before a ride. Toast and jam, a banana, or oatmeal. Your legs will thank you.',
  },

  // ─── CURIOSITY (Have you tried...) ────────────────────────────────────────
  {
    id: 'tip_curiosity_bikepacking',
    category: 'curiosity',
    levels: ['beginner', 'intermediate', 'advanced'],
    weekRange: null,
    body: 'Have you heard of bikepacking? It\'s just camping by bike — start small, one overnight, your existing kit. Half the magic is realising you can ride to a place and stay there.',
  },
  {
    id: 'tip_curiosity_cafe',
    category: 'curiosity',
    levels: ['beginner'],
    weekRange: null,
    body: 'Next weekend, ride to a cafe you\'ve never been to. A 15-minute detour on the way home. Suddenly cycling isn\'t just training — it\'s a key to places.',
  },
  {
    id: 'tip_curiosity_group',
    category: 'curiosity',
    levels: ['beginner', 'intermediate'],
    weekRange: { min: 6, max: 12 },
    body: 'Consider joining a local cycling group once you\'ve got a few weeks in. Being around other riders changes everything — no judgment, just people who get it.',
  },
  {
    id: 'tip_curiosity_gravel',
    category: 'curiosity',
    levels: ['beginner', 'intermediate'],
    weekRange: { min: 8, max: 12 },
    body: 'If you ride a road bike, try a gravel path or towpath. Wider tyres, looser surface, same bike. It\'s liberating.',
  },
  {
    id: 'tip_curiosity_charity',
    category: 'curiosity',
    levels: ['beginner', 'intermediate', 'advanced'],
    weekRange: null,
    body: 'Look for charity rides in your area. A structured 50 km ride with others gives you something to aim for.',
  },

  // ─── PLAN ADJUSTMENT (Dialling the plan up or down) ──────────────────────
  {
    id: 'tip_plan_struggling',
    category: 'plan_adjustment',
    levels: ['beginner', 'intermediate'],
    weekRange: null,
    body: 'If you\'re not finding the time for every session, that\'s totally fine — tell me in chat and we\'ll dial the plan back. Two consistent weeks beat one ambitious one.',
  },
  {
    id: 'tip_plan_easy',
    category: 'plan_adjustment',
    levels: ['beginner', 'intermediate'],
    weekRange: { min: 4, max: 12 },
    body: 'Feeling like the plan is too easy? Let me know in a check-in or chat and we\'ll add some intensity or distance. Easy to crank up, hard to pull back.',
  },
  {
    id: 'tip_plan_tired',
    category: 'plan_adjustment',
    levels: ['beginner', 'intermediate', 'advanced'],
    weekRange: null,
    body: 'Feeling fatigued? More rest is often the answer, not less. A recovery week every 4 weeks is normal.',
  },
  {
    id: 'tip_plan_life',
    category: 'plan_adjustment',
    levels: ['beginner', 'intermediate', 'advanced'],
    weekRange: null,
    body: 'Life happens. Work gets busy, you get ill, plans change. Tell me what\'s going on and we\'ll adjust. That\'s what the plan is for.',
  },
  {
    id: 'tip_plan_consistency',
    category: 'plan_adjustment',
    levels: ['beginner'],
    weekRange: { min: 1, max: 6 },
    body: 'Your only job right now is showing up. Perfect execution doesn\'t matter — three consistent weeks beats one perfect week.',
  },

  // ─── Extra variety ────────────────────────────────────────────────────────
  {
    id: 'tip_extra_weather',
    category: 'body',
    levels: ['beginner'],
    weekRange: null,
    body: 'Cold weather riding is just about layers — base layer, jersey, wind jacket. You feel better than you think once you get moving.',
  },
  {
    id: 'tip_extra_wind',
    category: 'body',
    levels: ['beginner', 'intermediate'],
    weekRange: null,
    body: 'Wind makes rides harder but also stronger. Lean into it on the days you have them — free strength training.',
  },
  {
    id: 'tip_extra_routes',
    category: 'curiosity',
    levels: ['beginner'],
    weekRange: null,
    body: 'Change your route every few weeks. New scenery, new roads, same fitness gains. Keeps it fresh.',
  },
  {
    id: 'tip_extra_friends',
    category: 'culture',
    levels: ['beginner', 'intermediate'],
    weekRange: null,
    body: 'Invite a friend to join a ride, even if they\'re not as fit. Slower pace, good company, and you\'re spreading the love.',
  },

  // ─── REGION + SEASON AWARE TIPS (added April 2026) ──────────────────────
  {
    id: 'tip_uk_cycling',
    category: 'culture',
    levels: ['beginner', 'intermediate'],
    weekRange: null,
    regions: ['UK'],
    seasons: null,
    body: 'British Cycling has a sportives finder on its website — hundreds of timed events run across the UK from spring to autumn. Worth a look once you\'re confident with 30+ km rides.',
  },
  {
    id: 'tip_ride_london',
    category: 'culture',
    levels: ['beginner', 'intermediate'],
    weekRange: null,
    regions: ['UK'],
    seasons: null,
    body: 'Ride London is the UK\'s biggest mass-participation event. The 30 km route is a great first goal if you\'re around the south-east.',
  },
  {
    id: 'tip_uk_cyclocross',
    category: 'culture',
    levels: ['beginner', 'intermediate'],
    weekRange: null,
    regions: ['UK'],
    seasons: { months: [9, 10, 11, 12] },
    body: 'Cyclocross season is starting in the UK — local clubs put on weekend events that are surprisingly accessible. A way to keep riding through winter.',
  },
  {
    id: 'tip_etape_du_tour',
    category: 'culture',
    levels: ['intermediate'],
    weekRange: null,
    regions: ['EU'],
    seasons: null,
    body: 'L\'Étape du Tour lets amateur riders ride a real Tour de France stage. Bucket-list tier — but there are shorter Étape Series rides scattered across France that are accessible for intermediate riders.',
  },
  {
    id: 'tip_maratona_dolomites',
    category: 'culture',
    levels: ['intermediate'],
    weekRange: null,
    regions: ['EU'],
    seasons: null,
    body: 'The Maratona dles Dolomites in Italy is one of Europe\'s most beautiful sportives. Has shorter routes for less-experienced riders too.',
  },
  {
    id: 'tip_gran_fondos_us',
    category: 'culture',
    levels: ['intermediate'],
    weekRange: null,
    regions: ['NA'],
    seasons: null,
    body: 'Have you looked at gran fondos in your state? America\'s gran-fondo scene has exploded over the last decade — Levi\'s GranFondo and the Belgian Waffle Ride are well-known. Most have a beginner-friendly distance.',
  },
  {
    id: 'tip_ragbrai',
    category: 'culture',
    levels: ['beginner', 'intermediate'],
    weekRange: null,
    regions: ['NA'],
    seasons: { months: [7] },
    body: 'RAGBRAI rolls across Iowa every July. Seven days, lots of beer, no real winners — possibly the most fun thing you can do on a bike if you want a community ride that isn\'t precious about pace.',
  },
  {
    id: 'tip_bowral_classic',
    category: 'culture',
    levels: ['beginner', 'intermediate'],
    weekRange: null,
    regions: ['AU'],
    seasons: null,
    body: 'The Bowral Classic and Snowies Ride are big NSW events with beginner-friendly distances. Worth knowing about as a first event goal.',
  },
  {
    id: 'tip_kepler_challenge',
    category: 'culture',
    levels: ['intermediate'],
    weekRange: null,
    regions: ['AU'],
    seasons: null,
    body: 'K2 (Kepler Challenge in NZ) has a road version that\'s a beautiful intro to NZ cycling culture.',
  },
  {
    id: 'tip_find_club',
    category: 'culture',
    levels: ['beginner', 'intermediate', 'advanced'],
    weekRange: null,
    regions: null,
    seasons: null,
    body: 'Have you looked for a cycling club near you? Most have weekend group rides at every pace — including a beginner pace. Way more fun than riding solo, and you\'ll learn road craft fast.',
  },
  {
    id: 'tip_spring_goal',
    category: 'culture',
    levels: ['beginner', 'intermediate'],
    weekRange: null,
    regions: ['NA', 'EU', 'UK'],
    seasons: { months: [3, 4, 5] },
    body: 'Spring is when most cycling event seasons kick off in the northern hemisphere. Find one 12 weeks out and use it as your next goal — having a date locks the habit in.',
  },
  {
    id: 'tip_watch_classics',
    category: 'culture',
    levels: ['beginner', 'intermediate'],
    weekRange: null,
    regions: null,
    seasons: { months: [3, 4] },
    body: 'If watching the pros is new to you — most major races have free YouTube highlights. The Spring Classics (Flanders, Roubaix, Liège) are gritty and brilliant. Tour / Giro / Vuelta are the headline acts.',
  },
  {
    id: 'tip_winter_lights',
    category: 'gear',
    levels: ['beginner', 'intermediate'],
    weekRange: null,
    regions: ['NA', 'EU', 'UK'],
    seasons: { months: [11, 12, 1, 2] },
    body: 'Daylight\'s short right now. If commuting in the dark feels off, get a couple of decent lights and reflective ankles bands — half a kilo of gear keeps the habit alive through winter.',
  },
  {
    id: 'tip_tour_month',
    category: 'culture',
    levels: ['beginner', 'intermediate'],
    weekRange: null,
    regions: null,
    seasons: { months: [7] },
    body: 'The Tour de France is on this month. Even an evening\'s highlights makes you a better cyclist — you start to notice pacing, positioning, why riders eat when they do.',
  },

  // ─── GEAR WITH INVENTORY GAPS ────────────────────────────────────────────────
  // Tips filtered to riders who DON'T have the item yet (requiresGap: 'itemId')
  {
    id: 'tip_gear_padded_shorts',
    category: 'gear',
    levels: ['beginner'],
    weekRange: { min: 2, max: 5 },
    requiresGap: 'paddedShorts',
    body: 'If your saddle is getting uncomfortable, try padded shorts before changing the saddle. £30 fix that beats a £150 saddle nine times out of ten.',
  },
  {
    id: 'tip_gear_lights',
    category: 'gear',
    levels: ['beginner'],
    weekRange: { min: 2, max: 6 },
    requiresGap: 'frontLight',
    body: 'Got front + rear lights yet? Even £30 USB lights make daylight rides safer and unlock evening commutes. UK riders — required by law from sunset.',
  },
  {
    id: 'tip_gear_puncture_kit',
    category: 'gear',
    levels: ['beginner'],
    weekRange: { min: 4, max: 6 },
    requiresGap: 'punctureKit',
    body: 'Fixing your first puncture is a rite of passage. Watch one YouTube tutorial — 5-minute job once you\'ve done it once. Throw a spare tube + tyre levers in a saddle bag.',
  },
  {
    id: 'tip_gear_track_pump',
    category: 'gear',
    levels: ['beginner'],
    weekRange: { min: 1, max: 3 },
    requiresGap: 'trackPump',
    body: 'A track pump at home (£15–30) is the small purchase that pays for itself fastest. Properly inflated tyres make every ride feel better.',
  },
  {
    id: 'tip_gear_cleats_curiosity',
    category: 'gear',
    levels: ['beginner'],
    weekRange: { min: 6, max: 10 },
    requiresGap: 'cleats',
    body: 'Curious about clipless pedals? They make every ride feel more connected to the bike. SPD-style is more forgiving than road cleats — start there. No rush — when current pedals feel limiting, that\'s the signal.',
  },
  {
    id: 'tip_gear_jersey',
    category: 'gear',
    levels: ['beginner'],
    weekRange: { min: 4, max: 8 },
    requiresGap: 'jersey',
    body: 'A cycling jersey isn\'t just lycra cosplay — the rear pockets are how riders carry phone, snacks, jacket. Game-changer once you ride more than 90 min.',
  },
  {
    id: 'tip_gear_gloves',
    category: 'gear',
    levels: ['beginner'],
    weekRange: { min: 2, max: 6 },
    requiresGap: 'gloves',
    body: 'Gloves are about hand fatigue, not crashes — vibration through the bars over an hour wears your hands out. Cheap fingerless ones (£15) make a real difference.',
  },
  {
    id: 'tip_gear_saddle_bag',
    category: 'gear',
    levels: ['beginner'],
    weekRange: { min: 3, max: 6 },
    requiresGap: 'saddleBag',
    body: 'A saddle bag is where your puncture kit lives so you don\'t forget it. £15 fix that means you\'re never stranded.',
  },
  {
    id: 'tip_routes_komoot',
    category: 'exploration',
    levels: ['beginner'],
    weekRange: { min: 1, max: 3 },
    body: 'Found any routes you like yet? Komoot\'s free tier and the Strava global heatmap show you where cyclists actually ride near you. Worth a poke around.',
  },
  {
    id: 'tip_clubs_first_ride',
    category: 'community',
    levels: ['beginner'],
    weekRange: { min: 4, max: 8 },
    body: 'Have you ever ridden in a group? Local clubs almost always have a beginners\' ride. Half the riding skill you don\'t even know about gets transferred in the first couple of group rides.',
  },
];

function getCatalog() {
  return CATALOG;
}

module.exports = { getCatalog };
