const { execSync } = require('child_process');
const path = require('path');

const ETAPA_REPO = path.resolve(process.env.ETAPA_REPO || path.join(__dirname, '../../../'));

function formatNotionUrl(taskId) {
  return `https://www.notion.so/${taskId.replace(/-/g, '')}`;
}

function createPRBody(groupName, tasks, agentIds = []) {
  const taskList = tasks
    .map(t => `- [${t.name}](${formatNotionUrl(t.id)}) — Status: ${t.status}`)
    .join('\n');

  const agentList = agentIds.length > 0 ? `\n**Spawned Agents:** ${agentIds.join(', ')}` : '';

  return `## Task Group: ${groupName}

**Tasks:**
${taskList}
${agentList}

**Status:** In Progress
**Started:** ${new Date().toISOString()}

---
🤖 Auto-generated by Task Builder plugin`;
}

async function createPR(groupName, tasks, agentIds = []) {
  try {
    const title = `Task Builder: ${groupName}`;
    const body = createPRBody(groupName, tasks, agentIds);

    // Create branch name from group name
    const branchName = `task-builder/${groupName.toLowerCase().replace(/\s+/g, '-')}-${Date.now()}`;

    // Execute git commands in the etapa repo
    const commands = [
      `cd ${ETAPA_REPO}`,
      `git checkout -b ${branchName}`,
      `git commit --allow-empty -m "Task Builder: ${groupName}"`,
      `git push origin ${branchName}`,
      `gh pr create --title "${title}" --body "${body.replace(/"/g, '\\"')}" --assignee honeybulr`
    ];

    const result = execSync(commands.join(' && '), {
      encoding: 'utf-8',
      stdio: ['pipe', 'pipe', 'pipe']
    });

    // Extract PR URL from result
    const match = result.match(/https:\/\/github\.com\/[^\/]+\/[^\/]+\/pull\/\d+/);
    const prUrl = match ? match[0] : null;

    return {
      success: true,
      prUrl,
      branchName,
      groupName
    };
  } catch (error) {
    console.error(`Failed to create PR: ${error.message}`);
    return {
      success: false,
      error: error.message,
      groupName
    };
  }
}

async function updatePRStatus(prNumber, status, notes = '') {
  try {
    const body = `## Status Update

**New Status:** ${status}
**Updated:** ${new Date().toISOString()}

${notes ? `**Notes:**\n${notes}` : ''}`;

    execSync(
      `cd ${ETAPA_REPO} && gh pr comment ${prNumber} --body "${body.replace(/"/g, '\\"')}"`,
      { encoding: 'utf-8' }
    );

    return { success: true, prNumber, status };
  } catch (error) {
    console.error(`Failed to update PR comment: ${error.message}`);
    return { success: false, error: error.message };
  }
}

module.exports = {
  createPR,
  updatePRStatus,
  createPRBody,
  formatNotionUrl
};
