/**
 * About & Legal — AI transparency, disclaimers, training sources, and legal links.
 */
import React from 'react';
import {
  View, Text, TouchableOpacity, ScrollView, StyleSheet, Linking, Image,
} from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { colors, fontFamily } from '../theme';

const FF = fontFamily;

const TRAINING_SOURCES = [
  { title: 'The Cyclist\'s Training Bible', author: 'Joe Friel', detail: 'Periodisation, threshold training, and structured plan design' },
  { title: 'The Time-Crunched Cyclist', author: 'Chris Carmichael', detail: 'Efficient training principles for busy athletes' },
  { title: '80/20 Polarised Training', author: 'Dr. Stephen Seiler', detail: 'Research on optimal intensity distribution' },
  { title: 'TrainerRoad & Wahoo SYSTM', author: '', detail: 'Structured workout methodology and interval design' },
  { title: 'British Cycling Pathways', author: '', detail: 'Coaching frameworks and rider development principles' },
  { title: 'Sports Science Research', author: '', detail: 'Progressive overload, recovery science, and injury prevention' },
];

const AI_PRINCIPLES = [
  'Progressive overload — weekly volume increases capped at 10%',
  'Polarised training — 80% easy / 20% hard intensity split',
  'Periodisation — base, build, peak, and taper phases',
  'Recovery weeks every 3–4 weeks with 30% volume reduction',
  'Taper protocols — 40–50% volume reduction before events',
  'Cross-training load factored into recovery planning',
];

export default function AboutScreen({ navigation }) {
  return (
    <View style={s.container}>
      <SafeAreaView style={s.safe}>
        <View style={s.header}>
          <TouchableOpacity onPress={() => navigation.goBack()} hitSlop={{ top: 12, bottom: 12, left: 12, right: 12 }}>
            <Text style={s.backArrow}>{'\u2190'}</Text>
          </TouchableOpacity>
          <Text style={s.headerTitle}>About Etapa</Text>
          <View style={{ width: 32 }} />
        </View>

        <ScrollView style={s.scroll} showsVerticalScrollIndicator={false}>
          {/* Logo & tagline */}
          <View style={s.logoSection}>
            <Image source={require('../../assets/icon.png')} style={s.logo} resizeMode="contain" />
            <Text style={s.appName}>Etapa</Text>
            <Text style={s.tagline}>AI-powered cycling coach</Text>
          </View>

          {/* AI Transparency */}
          <View style={s.card}>
            <View style={s.cardHeader}>
              <Text style={s.cardTitle}>Built with AI</Text>
            </View>
            <Text style={s.cardBody}>
              Every training plan, coaching conversation, session adjustment, and check-in message in Etapa is generated by artificial intelligence. We use Anthropic's Claude AI models to power the coaching experience.
            </Text>
            <Text style={s.cardBody}>
              Your AI coach draws on established cycling training science to create personalised, periodised plans — but it is not a human coach. Plans are generated algorithmically and should be treated as guidance, not prescriptions.
            </Text>
          </View>

          {/* Health Disclaimer */}
          <View style={[s.card, s.cardWarning]}>
            <View style={s.cardHeader}>
              <Text style={s.cardTitle}>Health Disclaimer</Text>
            </View>
            <Text style={s.cardBody}>
              Etapa is not a medical service and does not provide medical advice. Training plans are generated by AI and are not reviewed by a healthcare professional.
            </Text>
            <Text style={s.cardBody}>
              Always consult your doctor before beginning any new exercise programme, especially if you have pre-existing health conditions, injuries, or have been inactive for an extended period. Stop exercising immediately if you experience pain, dizziness, or shortness of breath.
            </Text>
            <Text style={s.cardBody}>
              You train at your own risk. Etapa and its creators accept no liability for injuries or health issues arising from use of AI-generated training plans.
            </Text>
          </View>

          {/* Training Sources */}
          <View style={s.card}>
            <View style={s.cardHeader}>
              <Text style={s.cardTitle}>Training Science Sources</Text>
            </View>
            <Text style={s.cardBody}>
              Our AI coaches are instructed to follow established cycling training principles from these sources:
            </Text>
            {TRAINING_SOURCES.map((src, i) => (
              <View key={i} style={s.sourceRow}>
                <View style={s.sourceDot} />
                <View style={s.sourceContent}>
                  <Text style={s.sourceTitle}>
                    {src.title}{src.author ? <Text style={s.sourceAuthor}> — {src.author}</Text> : null}
                  </Text>
                  <Text style={s.sourceDetail}>{src.detail}</Text>
                </View>
              </View>
            ))}
          </View>

          {/* Key Principles */}
          <View style={s.card}>
            <View style={s.cardHeader}>
              <Text style={s.cardTitle}>How Plans Are Built</Text>
            </View>
            <Text style={s.cardBody}>
              Every plan follows these evidence-based principles:
            </Text>
            {AI_PRINCIPLES.map((p, i) => (
              <View key={i} style={s.principleRow}>
                <Text style={s.principleCheck}>{'\u2713'}</Text>
                <Text style={s.principleText}>{p}</Text>
              </View>
            ))}
          </View>

          {/* AI Limitations */}
          <View style={s.card}>
            <View style={s.cardHeader}>
              <Text style={s.cardTitle}>AI Limitations</Text>
            </View>
            <Text style={s.cardBody}>
              While our AI is trained on quality cycling science, it has limitations you should be aware of:
            </Text>
            <Text style={s.cardBody}>
              {'\u2022'} It cannot assess your physical condition, injury history, or biomechanics{'\n'}
              {'\u2022'} It may occasionally suggest workouts that don't suit your specific situation{'\n'}
              {'\u2022'} It cannot replace the judgement of a qualified human coach or physiotherapist{'\n'}
              {'\u2022'} Training advice is general in nature and not tailored to medical conditions{'\n'}
              {'\u2022'} AI responses may occasionally contain errors or inconsistencies
            </Text>
            <Text style={s.cardBody}>
              Use your own judgement. If something doesn't feel right, modify or skip the session.
            </Text>
          </View>

          {/* Legal Links */}
          <View style={s.card}>
            <View style={s.cardHeader}>
              <Text style={s.cardTitle}>Legal</Text>
            </View>
            <TouchableOpacity style={s.legalRow} onPress={() => Linking.openURL('https://getetapa.com/terms.html')}>
              <Text style={s.legalText}>Terms of Use</Text>
              <Text style={s.legalArrow}>{'\u203A'}</Text>
            </TouchableOpacity>
            <TouchableOpacity style={s.legalRow} onPress={() => Linking.openURL('https://getetapa.com/privacy.html')}>
              <Text style={s.legalText}>Privacy Policy</Text>
              <Text style={s.legalArrow}>{'\u203A'}</Text>
            </TouchableOpacity>
          </View>

          {/* Powered by */}
          <View style={s.poweredBy}>
            <Text style={s.poweredByText}>AI powered by Anthropic Claude</Text>
            <Text style={s.poweredByText}>Training science, not guesswork</Text>
          </View>

          <View style={{ height: 40 }} />
        </ScrollView>
      </SafeAreaView>
    </View>
  );
}

const s = StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.bg },
  safe: { flex: 1 },
  header: {
    flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between',
    paddingHorizontal: 20, paddingVertical: 14,
  },
  backArrow: { fontSize: 22, color: colors.text },
  headerTitle: { fontSize: 17, fontWeight: '600', fontFamily: FF.semibold, color: colors.text },
  scroll: { flex: 1, paddingHorizontal: 20 },

  logoSection: { alignItems: 'center', paddingVertical: 32 },
  logo: { width: 64, height: 64, borderRadius: 14, marginBottom: 12 },
  appName: { fontSize: 24, fontWeight: '700', fontFamily: FF.semibold, color: colors.text },
  tagline: { fontSize: 14, fontWeight: '400', fontFamily: FF.regular, color: colors.textMid, marginTop: 4 },

  card: {
    backgroundColor: colors.surface, borderRadius: 14, padding: 18, marginBottom: 14,
    borderWidth: 1, borderColor: colors.border,
  },
  cardWarning: { borderColor: 'rgba(234,179,8,0.3)' },
  cardHeader: { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 12 },
  cardIcon: { fontSize: 18 },
  cardTitle: { fontSize: 16, fontWeight: '600', fontFamily: FF.semibold, color: colors.text },
  cardBody: { fontSize: 13, fontWeight: '400', fontFamily: FF.regular, color: colors.textMid, lineHeight: 20, marginBottom: 8 },

  sourceRow: { flexDirection: 'row', alignItems: 'flex-start', gap: 10, marginTop: 8 },
  sourceDot: { width: 6, height: 6, borderRadius: 3, backgroundColor: colors.primary, marginTop: 7 },
  sourceContent: { flex: 1 },
  sourceTitle: { fontSize: 13, fontWeight: '600', fontFamily: FF.semibold, color: colors.text },
  sourceAuthor: { fontWeight: '400', color: colors.textMid },
  sourceDetail: { fontSize: 12, fontWeight: '400', fontFamily: FF.regular, color: colors.textMuted, marginTop: 2 },

  principleRow: { flexDirection: 'row', alignItems: 'flex-start', gap: 8, marginTop: 6 },
  principleCheck: { color: '#22C55E', fontSize: 13, fontWeight: '600', width: 16, marginTop: 1 },
  principleText: { fontSize: 13, fontWeight: '400', fontFamily: FF.regular, color: colors.textMid, flex: 1, lineHeight: 19 },

  legalRow: {
    flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between',
    paddingVertical: 14, borderTopWidth: 1, borderTopColor: colors.border,
  },
  legalText: { fontSize: 15, fontWeight: '500', fontFamily: FF.medium, color: colors.text },
  legalArrow: { fontSize: 20, color: colors.textFaint },

  poweredBy: { alignItems: 'center', paddingVertical: 24 },
  poweredByText: { fontSize: 12, fontWeight: '400', fontFamily: FF.regular, color: colors.textFaint, marginBottom: 4 },
});
