// Test scenarios — single source of truth shared between CLI runner and dashboard
export const SCENARIOS = [
  { name: 'Beginner - General Fitness - 3 days/week', goal: { id: 'g1', goalType: 'improve', cyclingType: 'road', planName: 'Get Fit Plan' }, config: { id: 'c1', daysPerWeek: 3, weeks: 8, trainingTypes: ['outdoor'], availableDays: ['monday', 'wednesday', 'saturday'], fitnessLevel: 'beginner', startDate: '2026-04-06' } },
  { name: 'Intermediate - Race Prep - 4 days/week - 12 weeks', goal: { id: 'g2', goalType: 'race', cyclingType: 'road', eventName: 'London to Brighton', targetDistance: 90, targetDate: '2026-07-05', planName: 'L2B Prep' }, config: { id: 'c2', daysPerWeek: 4, weeks: 12, trainingTypes: ['outdoor'], availableDays: ['tuesday', 'thursday', 'saturday', 'sunday'], fitnessLevel: 'intermediate', startDate: '2026-04-06' } },
  { name: 'Advanced - 5 days + strength - 10 weeks', goal: { id: 'g3', goalType: 'distance', cyclingType: 'road', targetDistance: 160, targetDate: '2026-06-20', planName: 'Century Ride Prep' }, config: { id: 'c3', daysPerWeek: 5, weeks: 10, trainingTypes: ['outdoor', 'strength'], availableDays: ['monday', 'tuesday', 'thursday', 'friday', 'sunday'], fitnessLevel: 'advanced', startDate: '2026-04-13', crossTrainingDays: { wednesday: 'yoga' } } },
  { name: 'Expert - 6 days + recurring group ride - 8 weeks', goal: { id: 'g4', goalType: 'race', cyclingType: 'road', eventName: 'Gran Fondo', targetDistance: 130, targetDate: '2026-06-07', planName: 'Gran Fondo Prep' }, config: { id: 'c4', daysPerWeek: 6, weeks: 8, trainingTypes: ['outdoor'], availableDays: ['monday', 'tuesday', 'wednesday', 'thursday', 'saturday', 'sunday'], fitnessLevel: 'expert', startDate: '2026-04-06', recurringRides: [{ id: 'rr1', day: 'saturday', durationMins: 120, distanceKm: 60, notes: 'Club Ride' }], longRideDay: 'sunday' } },
  { name: 'Beginner - 2 days/week - 4 weeks (minimum)', goal: { id: 'g5', goalType: 'improve', cyclingType: 'road', planName: 'Quick Start' }, config: { id: 'c5', daysPerWeek: 2, weeks: 4, trainingTypes: ['outdoor'], availableDays: ['wednesday', 'sunday'], fitnessLevel: 'beginner', startDate: '2026-04-08' } },
  { name: 'Wednesday start + 2 organised rides', goal: { id: 'g6', goalType: 'race', cyclingType: 'road', eventName: 'Sportive', targetDistance: 100, targetDate: '2026-06-14', planName: 'Sportive Plan' }, config: { id: 'c6', daysPerWeek: 3, weeks: 9, trainingTypes: ['outdoor'], availableDays: ['tuesday', 'thursday', 'saturday'], fitnessLevel: 'intermediate', startDate: '2026-04-08', oneOffRides: [{ date: '2026-04-10', durationMins: 90, distanceKm: 40, notes: 'Charity Ride' }, { date: '2026-04-13', durationMins: 120, distanceKm: 55, notes: 'Sportive Recce' }] } },
  { name: 'Saturday start + organised ride next day', goal: { id: 'g7', goalType: 'distance', cyclingType: 'road', targetDistance: 80, targetDate: '2026-06-30', planName: 'Build Plan' }, config: { id: 'c7', daysPerWeek: 4, weeks: 10, trainingTypes: ['outdoor'], availableDays: ['monday', 'wednesday', 'friday', 'sunday'], fitnessLevel: 'advanced', startDate: '2026-04-18', oneOffRides: [{ date: '2026-04-19', durationMins: 150, distanceKm: 70, notes: 'Audax 70k' }] } },
  { name: 'E-bike beginner - 3 days/week - 8 weeks', goal: { id: 'g8', goalType: 'improve', cyclingType: 'ebike', planName: 'E-Bike Explorer' }, config: { id: 'c8', daysPerWeek: 3, weeks: 8, trainingTypes: ['outdoor'], availableDays: ['tuesday', 'thursday', 'saturday'], fitnessLevel: 'beginner', startDate: '2026-04-06' } },
  { name: 'Mixed indoor/outdoor + strength - 6 weeks', goal: { id: 'g9', goalType: 'improve', cyclingType: 'road', planName: 'Winter Fitness' }, config: { id: 'c9', daysPerWeek: 4, weeks: 6, trainingTypes: ['outdoor', 'indoor', 'strength'], availableDays: ['monday', 'wednesday', 'friday', 'sunday'], fitnessLevel: 'intermediate', startDate: '2026-04-06', crossTrainingDays: { tuesday: 'swimming', thursday: 'running' } } },
  { name: '24-week plan with elevation + recurring rides', goal: { id: 'g10', goalType: 'race', cyclingType: 'road', eventName: 'Etape du Tour', targetDistance: 170, targetElevation: 4500, targetTime: 9, targetDate: '2026-09-20', planName: 'Etape Prep' }, config: { id: 'c10', daysPerWeek: 5, weeks: 24, trainingTypes: ['outdoor', 'strength'], availableDays: ['monday', 'tuesday', 'thursday', 'saturday', 'sunday'], fitnessLevel: 'advanced', startDate: '2026-04-06', longRideDay: 'sunday', recurringRides: [{ id: 'rr2', day: 'saturday', durationMins: 90, distanceKm: 45, notes: 'Group Ride' }], crossTrainingDays: { wednesday: 'core workout' } } },
  { name: 'Edge: organised ride on plan start day', goal: { id: 'g11', goalType: 'improve', cyclingType: 'road', planName: 'Start with Event' }, config: { id: 'c11', daysPerWeek: 3, weeks: 6, trainingTypes: ['outdoor'], availableDays: ['monday', 'wednesday', 'friday'], fitnessLevel: 'intermediate', startDate: '2026-04-06', oneOffRides: [{ date: '2026-04-06', durationMins: 120, distanceKm: 50, notes: 'Kickoff Ride' }] } },
  { name: 'Edge: 3 consecutive organised rides', goal: { id: 'g12', goalType: 'race', cyclingType: 'road', eventName: 'Multi-day Tour', targetDate: '2026-06-28', planName: 'Tour Prep' }, config: { id: 'c12', daysPerWeek: 4, weeks: 10, trainingTypes: ['outdoor'], availableDays: ['monday', 'wednesday', 'friday', 'sunday'], fitnessLevel: 'intermediate', startDate: '2026-04-20', oneOffRides: [{ date: '2026-05-15', durationMins: 180, distanceKm: 80, notes: 'Stage 1 Recce' }, { date: '2026-05-16', durationMins: 150, distanceKm: 65, notes: 'Stage 2 Recce' }, { date: '2026-05-17', durationMins: 120, distanceKm: 50, notes: 'Stage 3 Recce' }] } },
  { name: 'Edge: organised ride 2 days before event', goal: { id: 'g13', goalType: 'race', cyclingType: 'road', eventName: 'Local Crit', targetDistance: 40, targetDate: '2026-05-17', planName: 'Crit Plan' }, config: { id: 'c13', daysPerWeek: 3, weeks: 6, trainingTypes: ['outdoor'], availableDays: ['tuesday', 'thursday', 'saturday'], fitnessLevel: 'advanced', startDate: '2026-04-06', oneOffRides: [{ date: '2026-05-15', durationMins: 60, distanceKm: 25, notes: 'Pre-race shakeout' }] } },
  { name: 'Conflict: recurring vs organised same Saturday', goal: { id: 'g14', goalType: 'improve', cyclingType: 'road', planName: 'Conflict Test' }, config: { id: 'c14', daysPerWeek: 3, weeks: 6, trainingTypes: ['outdoor'], availableDays: ['tuesday', 'thursday', 'saturday'], fitnessLevel: 'intermediate', startDate: '2026-04-06', recurringRides: [{ id: 'rr3', day: 'saturday', durationMins: 90, distanceKm: 40, notes: 'Club Ride' }], oneOffRides: [{ date: '2026-04-18', durationMins: 180, distanceKm: 80, notes: 'Charity Sportive' }] } },
  { name: 'Minimal: 1 day/week - 8 weeks', goal: { id: 'g15', goalType: 'improve', cyclingType: 'road', planName: 'Weekend Warrior' }, config: { id: 'c15', daysPerWeek: 1, weeks: 8, trainingTypes: ['outdoor'], availableDays: ['sunday'], fitnessLevel: 'beginner', startDate: '2026-04-06' } },
  { name: 'Friday start + organised ride on Sunday', goal: { id: 'g16', goalType: 'race', cyclingType: 'road', eventName: 'TT', targetDistance: 25, targetDate: '2026-06-06', planName: 'TT Prep' }, config: { id: 'c16', daysPerWeek: 3, weeks: 8, trainingTypes: ['outdoor'], availableDays: ['monday', 'wednesday', 'friday'], fitnessLevel: 'intermediate', startDate: '2026-04-10', oneOffRides: [{ date: '2026-04-12', durationMins: 60, distanceKm: 25, notes: 'Test TT effort' }] } },
  { name: 'Sunday start - Monday snap edge case', goal: { id: 'g17', goalType: 'improve', cyclingType: 'road', planName: 'Sunday Starter' }, config: { id: 'c17', daysPerWeek: 3, weeks: 6, trainingTypes: ['outdoor'], availableDays: ['tuesday', 'thursday', 'sunday'], fitnessLevel: 'beginner', startDate: '2026-04-12' } },
  { name: 'Kitchen sink: expert, all options, max complexity', goal: { id: 'g18', goalType: 'race', cyclingType: 'road', eventName: 'Marmotte', targetDistance: 175, targetElevation: 5000, targetTime: 10, targetDate: '2026-08-30', planName: 'Marmotte Beast Mode' }, config: { id: 'c18', daysPerWeek: 6, weeks: 20, trainingTypes: ['outdoor', 'indoor', 'strength'], availableDays: ['monday', 'tuesday', 'wednesday', 'friday', 'saturday', 'sunday'], fitnessLevel: 'expert', startDate: '2026-04-13', longRideDay: 'sunday', recurringRides: [{ id: 'rr4', day: 'saturday', durationMins: 150, distanceKm: 70, elevationM: 800, notes: 'Mountain Group Ride' }, { id: 'rr5', day: 'wednesday', durationMins: 60, distanceKm: 25, notes: 'Track Night' }], oneOffRides: [{ date: '2026-05-10', durationMins: 240, distanceKm: 100, elevationM: 2000, notes: 'Recce Ride A' }, { date: '2026-06-14', durationMins: 300, distanceKm: 140, elevationM: 3500, notes: 'Full Dress Rehearsal' }, { date: '2026-07-19', durationMins: 180, distanceKm: 90, elevationM: 1500, notes: 'Sharpener' }], crossTrainingDays: { thursday: 'yoga', friday: 'core workout' } } },
  { name: 'Beginner Get Into Cycling - 12 weeks', goal: { id: 'g19', goalType: 'beginner', cyclingType: 'road', planName: 'Get Into Cycling' }, config: { id: 'c19', daysPerWeek: 3, weeks: 12, trainingTypes: ['outdoor'], availableDays: ['tuesday', 'thursday', 'saturday'], fitnessLevel: 'beginner', startDate: '2026-04-06' } },
  { name: 'Intermediate with strength focus - 8 weeks', goal: { id: 'g20', goalType: 'improve', cyclingType: 'road', planName: 'Strength Builder' }, config: { id: 'c20', daysPerWeek: 4, weeks: 8, trainingTypes: ['outdoor', 'strength'], availableDays: ['monday', 'wednesday', 'friday', 'sunday'], fitnessLevel: 'intermediate', startDate: '2026-04-06', crossTrainingDays: { tuesday: 'running', thursday: 'swimming' } } },
  { name: 'Short race plan - 6 weeks with taper', goal: { id: 'g21', goalType: 'race', cyclingType: 'road', eventName: '50k TT', targetDistance: 50, targetDate: '2026-05-18', planName: '50k TT Prep' }, config: { id: 'c21', daysPerWeek: 4, weeks: 6, trainingTypes: ['outdoor'], availableDays: ['tuesday', 'wednesday', 'friday', 'sunday'], fitnessLevel: 'advanced', startDate: '2026-04-06' } },
  { name: 'E-bike intermediate with elevation goal', goal: { id: 'g22', goalType: 'distance', cyclingType: 'ebike', eventName: 'Peak District Loop', targetDistance: 100, targetElevation: 2000, targetDate: '2026-07-12', planName: 'E-Bike Peak District' }, config: { id: 'c22', daysPerWeek: 3, weeks: 12, trainingTypes: ['outdoor'], availableDays: ['wednesday', 'saturday', 'sunday'], fitnessLevel: 'intermediate', startDate: '2026-04-13', longRideDay: 'sunday' } },
  { name: 'All features: recurring + strength + cross-training', goal: { id: 'g23', goalType: 'race', cyclingType: 'road', eventName: 'Century Ride', targetDistance: 160, targetDate: '2026-06-21', planName: 'Century All-In' }, config: { id: 'c23', daysPerWeek: 5, weeks: 10, trainingTypes: ['outdoor', 'indoor', 'strength'], availableDays: ['monday', 'tuesday', 'thursday', 'saturday', 'sunday'], fitnessLevel: 'advanced', startDate: '2026-04-13', longRideDay: 'sunday', recurringRides: [{ id: 'rr6', day: 'saturday', durationMins: 120, distanceKm: 55, notes: 'Weekend Club Ride' }], crossTrainingDays: { wednesday: 'yoga', friday: 'running' } } },
  { name: 'Beginner with target time - 80km in 5 hours', goal: { id: 'g24', goalType: 'distance', cyclingType: 'road', targetDistance: 80, targetTime: 5, targetDate: '2026-07-05', planName: '80k Target' }, config: { id: 'c24', daysPerWeek: 3, weeks: 12, trainingTypes: ['outdoor'], availableDays: ['tuesday', 'thursday', 'sunday'], fitnessLevel: 'beginner', startDate: '2026-04-06' } },
  { name: 'Cross-training: running 3x/week (injury prevention)', goal: { id: 'g25', goalType: 'improve', cyclingType: 'road', planName: 'Runner-Cyclist Plan' }, config: { id: 'c25', daysPerWeek: 4, weeks: 8, trainingTypes: ['outdoor'], availableDays: ['monday', 'wednesday', 'friday', 'sunday'], fitnessLevel: 'intermediate', startDate: '2026-04-06', crossTrainingDays: { tuesday: 'running', thursday: 'running', saturday: 'running' } } },
  { name: 'Cross-training: rowing + swimming (mixed impact)', goal: { id: 'g26', goalType: 'race', cyclingType: 'road', eventName: 'Sprint Triathlon', targetDistance: 40, targetDate: '2026-06-28', planName: 'Tri Bike Prep' }, config: { id: 'c26', daysPerWeek: 3, weeks: 10, trainingTypes: ['outdoor', 'strength'], availableDays: ['monday', 'wednesday', 'saturday'], fitnessLevel: 'advanced', startDate: '2026-04-13', crossTrainingDays: { tuesday: 'rowing', thursday: 'swimming', friday: 'running' } } },
  { name: 'Cross-training: yoga + pilates (low impact)', goal: { id: 'g27', goalType: 'improve', cyclingType: 'road', planName: 'Balanced Wellness' }, config: { id: 'c27', daysPerWeek: 4, weeks: 8, trainingTypes: ['outdoor'], availableDays: ['monday', 'tuesday', 'thursday', 'saturday'], fitnessLevel: 'intermediate', startDate: '2026-04-06', crossTrainingDays: { wednesday: 'yoga', friday: 'pilates', sunday: 'yoga' } } },
  { name: 'Cross-training: gym + running (max stress)', goal: { id: 'g28', goalType: 'distance', cyclingType: 'road', targetDistance: 100, targetDate: '2026-07-19', planName: 'Ironman Bike Leg' }, config: { id: 'c28', daysPerWeek: 4, weeks: 12, trainingTypes: ['outdoor'], availableDays: ['monday', 'tuesday', 'thursday', 'saturday'], fitnessLevel: 'advanced', startDate: '2026-04-13', longRideDay: 'saturday', crossTrainingDays: { wednesday: 'weight training', friday: 'running', sunday: 'hiking' } } },
  { name: 'Cross-training: multi-activity days (high fatigue)', goal: { id: 'g29', goalType: 'improve', cyclingType: 'road', planName: 'Multi-Sport Plan' }, config: { id: 'c29', daysPerWeek: 3, weeks: 8, trainingTypes: ['outdoor'], availableDays: ['monday', 'wednesday', 'saturday'], fitnessLevel: 'intermediate', startDate: '2026-04-06', crossTrainingDays: { tuesday: 'running', thursday: 'swimming', friday: 'rowing', sunday: 'hiking' } } },
  { name: 'Cross-training + recurring: run before club ride', goal: { id: 'g30', goalType: 'improve', cyclingType: 'road', planName: 'Multi-Sport Club' }, config: { id: 'c30', daysPerWeek: 4, weeks: 8, trainingTypes: ['outdoor'], availableDays: ['monday', 'tuesday', 'thursday', 'saturday'], fitnessLevel: 'intermediate', startDate: '2026-04-06', recurringRides: [{ id: 'rr7', day: 'saturday', durationMins: 120, distanceKm: 50, notes: 'Club Ride' }], crossTrainingDays: { wednesday: 'running', friday: 'running', sunday: 'yoga' } } },

  // ── Regression tests ──────────────────────────────────────────────────────────
  // Each one locks down a specific bug the user reported. If any of these
  // fails, the bug has returned.

  // Bug: "I selected 3 rides per week but got 1 ride + 1 strength session".
  // Root cause: ambiguous prompt + beginner flow injected strength unconditionally
  // + example strength activity in prompt even when not requested.
  { name: 'REGRESSION: 3 rides/week outdoor only, NO strength', goal: { id: 'reg1', goalType: 'improve', cyclingType: 'road', planName: 'Reg #1' }, config: { id: 'creg1', daysPerWeek: 3, weeks: 6, trainingTypes: ['outdoor'], sessionCounts: { outdoor: 3 }, availableDays: ['monday', 'wednesday', 'saturday'], fitnessLevel: 'intermediate', startDate: '2026-04-06' } },

  // Bug: beginner flow silently adding strength from week 3.
  { name: 'REGRESSION: beginner flow, outdoor only, NO strength', goal: { id: 'reg2', goalType: 'beginner', cyclingType: 'road', planName: 'Reg #2' }, config: { id: 'creg2', daysPerWeek: 3, weeks: 12, trainingTypes: ['outdoor'], sessionCounts: { outdoor: 3 }, availableDays: ['tuesday', 'thursday', 'saturday'], fitnessLevel: 'beginner', startDate: '2026-04-06' } },

  // Positive test: when strength IS requested, plan must include exactly that count.
  { name: 'REGRESSION: 3 rides + 1 strength explicitly requested', goal: { id: 'reg3', goalType: 'improve', cyclingType: 'road', planName: 'Reg #3' }, config: { id: 'creg3', daysPerWeek: 4, weeks: 6, trainingTypes: ['outdoor', 'strength'], sessionCounts: { outdoor: 3, strength: 1 }, availableDays: ['monday', 'wednesday', 'friday', 'saturday'], fitnessLevel: 'intermediate', startDate: '2026-04-06' } },

  // High-count test: 5 rides/week must be honoured in build phase.
  { name: 'REGRESSION: 5 rides/week honoured in build phase', goal: { id: 'reg4', goalType: 'distance', cyclingType: 'road', targetDistance: 120, planName: 'Reg #4' }, config: { id: 'creg4', daysPerWeek: 5, weeks: 8, trainingTypes: ['outdoor'], sessionCounts: { outdoor: 5 }, availableDays: ['monday', 'tuesday', 'thursday', 'saturday', 'sunday'], fitnessLevel: 'advanced', startDate: '2026-04-06' } },

  // ── "Just get better" flow (goalType: 'improve') ──
  // These mirror what the new HomeScreen handleQuickPlan creates: an improve
  // goal with no target distance / event name / target date. Covers the
  // range of typical user configurations that hit this code path.
  { name: 'JUST GET BETTER: beginner 2 days/week 4 weeks', goal: { id: 'jgb1', goalType: 'improve', cyclingType: 'mixed', planName: 'Keep improving' }, config: { id: 'cjgb1', daysPerWeek: 2, weeks: 4, trainingTypes: ['outdoor'], availableDays: ['wednesday', 'saturday'], fitnessLevel: 'beginner', startDate: '2026-04-06' } },
  { name: 'JUST GET BETTER: intermediate 3 days/week 8 weeks', goal: { id: 'jgb2', goalType: 'improve', cyclingType: 'mixed', planName: 'Keep improving' }, config: { id: 'cjgb2', daysPerWeek: 3, weeks: 8, trainingTypes: ['outdoor'], availableDays: ['tuesday', 'thursday', 'saturday'], fitnessLevel: 'intermediate', startDate: '2026-04-06' } },
  { name: 'JUST GET BETTER: intermediate 4 days + strength 12 weeks', goal: { id: 'jgb3', goalType: 'improve', cyclingType: 'mixed', planName: 'Keep improving' }, config: { id: 'cjgb3', daysPerWeek: 4, weeks: 12, trainingTypes: ['outdoor', 'strength'], availableDays: ['monday', 'wednesday', 'friday', 'saturday'], fitnessLevel: 'intermediate', startDate: '2026-04-06' } },
  { name: 'JUST GET BETTER: advanced 5 days outdoor+indoor 10 weeks', goal: { id: 'jgb4', goalType: 'improve', cyclingType: 'road', planName: 'Keep improving' }, config: { id: 'cjgb4', daysPerWeek: 5, weeks: 10, trainingTypes: ['outdoor', 'indoor'], availableDays: ['monday', 'tuesday', 'thursday', 'saturday', 'sunday'], fitnessLevel: 'advanced', startDate: '2026-04-06' } },
  { name: 'JUST GET BETTER: e-bike intermediate 3 days 6 weeks', goal: { id: 'jgb5', goalType: 'improve', cyclingType: 'ebike', planName: 'Keep improving' }, config: { id: 'cjgb5', daysPerWeek: 3, weeks: 6, trainingTypes: ['outdoor'], availableDays: ['tuesday', 'thursday', 'sunday'], fitnessLevel: 'intermediate', startDate: '2026-04-06' } },
  { name: 'JUST GET BETTER: long ride on Sunday picked explicitly', goal: { id: 'jgb6', goalType: 'improve', cyclingType: 'road', planName: 'Keep improving' }, config: { id: 'cjgb6', daysPerWeek: 4, weeks: 8, trainingTypes: ['outdoor'], availableDays: ['tuesday', 'thursday', 'saturday', 'sunday'], fitnessLevel: 'intermediate', startDate: '2026-04-06', longRideDay: 'sunday' } },

  // ── "Getting started" flow (goalType: 'beginner') ──
  // The Get into Cycling pathway. Covers short/long plans, with and without
  // strength, and the range of weekly volumes beginners typically pick.
  { name: 'GETTING STARTED: 2 days/week 6 weeks, pure outdoor', goal: { id: 'gs1', goalType: 'beginner', cyclingType: 'road', planName: 'Get Into Cycling' }, config: { id: 'cgs1', daysPerWeek: 2, weeks: 6, trainingTypes: ['outdoor'], availableDays: ['wednesday', 'saturday'], fitnessLevel: 'beginner', startDate: '2026-04-06' } },
  { name: 'GETTING STARTED: 3 days/week 8 weeks, pure outdoor', goal: { id: 'gs2', goalType: 'beginner', cyclingType: 'road', planName: 'Get Into Cycling' }, config: { id: 'cgs2', daysPerWeek: 3, weeks: 8, trainingTypes: ['outdoor'], availableDays: ['tuesday', 'thursday', 'saturday'], fitnessLevel: 'beginner', startDate: '2026-04-06' } },
  { name: 'GETTING STARTED: 3 days/week 12 weeks, full couch-to-25km', goal: { id: 'gs3', goalType: 'beginner', cyclingType: 'road', planName: 'Get Into Cycling' }, config: { id: 'cgs3', daysPerWeek: 3, weeks: 12, trainingTypes: ['outdoor'], availableDays: ['monday', 'wednesday', 'saturday'], fitnessLevel: 'beginner', startDate: '2026-04-06' } },
  { name: 'GETTING STARTED: 2 days/week 12 weeks, slow build', goal: { id: 'gs4', goalType: 'beginner', cyclingType: 'road', planName: 'Get Into Cycling' }, config: { id: 'cgs4', daysPerWeek: 2, weeks: 12, trainingTypes: ['outdoor'], availableDays: ['wednesday', 'sunday'], fitnessLevel: 'beginner', startDate: '2026-04-06' } },
  { name: 'GETTING STARTED: 3 rides + 1 strength, 10 weeks', goal: { id: 'gs5', goalType: 'beginner', cyclingType: 'road', planName: 'Get Into Cycling' }, config: { id: 'cgs5', daysPerWeek: 4, weeks: 10, trainingTypes: ['outdoor', 'strength'], sessionCounts: { outdoor: 3, strength: 1 }, availableDays: ['tuesday', 'wednesday', 'thursday', 'saturday'], fitnessLevel: 'beginner', startDate: '2026-04-06' } },
  { name: 'GETTING STARTED: e-bike 2 days/week 8 weeks', goal: { id: 'gs6', goalType: 'beginner', cyclingType: 'ebike', planName: 'Get Into Cycling' }, config: { id: 'cgs6', daysPerWeek: 2, weeks: 8, trainingTypes: ['outdoor'], availableDays: ['wednesday', 'saturday'], fitnessLevel: 'beginner', startDate: '2026-04-06' } },
  { name: 'GETTING STARTED: long ride pre-set to Sunday', goal: { id: 'gs7', goalType: 'beginner', cyclingType: 'road', planName: 'Get Into Cycling' }, config: { id: 'cgs7', daysPerWeek: 3, weeks: 8, trainingTypes: ['outdoor'], availableDays: ['tuesday', 'thursday', 'sunday'], fitnessLevel: 'beginner', startDate: '2026-04-06', longRideDay: 'sunday' } },

  // ── "Just get better" edge cases — deliberately random/awkward setups ──
  { name: 'EDGE (just-better): weekday warrior M/W/F only', goal: { id: 'eb1', goalType: 'improve', cyclingType: 'road', planName: 'Keep improving' }, config: { id: 'ceb1', daysPerWeek: 3, weeks: 8, trainingTypes: ['outdoor'], availableDays: ['monday', 'wednesday', 'friday'], fitnessLevel: 'beginner', startDate: '2026-04-06' } },
  { name: 'EDGE (just-better): weekends-only 2-day intermediate', goal: { id: 'eb2', goalType: 'improve', cyclingType: 'road', planName: 'Keep improving' }, config: { id: 'ceb2', daysPerWeek: 2, weeks: 8, trainingTypes: ['outdoor'], availableDays: ['saturday', 'sunday'], fitnessLevel: 'intermediate', startDate: '2026-04-06', longRideDay: 'saturday' } },
  { name: 'EDGE (just-better): 1 day/week commuter absolute minimum', goal: { id: 'eb3', goalType: 'improve', cyclingType: 'road', planName: 'Keep improving' }, config: { id: 'ceb3', daysPerWeek: 1, weeks: 6, trainingTypes: ['outdoor'], availableDays: ['saturday'], fitnessLevel: 'beginner', startDate: '2026-04-06' } },
  { name: 'EDGE (just-better): every day available, 5 sessions incl. strength', goal: { id: 'eb4', goalType: 'improve', cyclingType: 'road', planName: 'Keep improving' }, config: { id: 'ceb4', daysPerWeek: 5, weeks: 8, trainingTypes: ['outdoor', 'indoor', 'strength'], sessionCounts: { outdoor: 3, indoor: 1, strength: 1 }, availableDays: ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'], fitnessLevel: 'intermediate', startDate: '2026-04-06', longRideDay: 'saturday' } },
  { name: 'EDGE (just-better): mid-week long ride on Wednesday', goal: { id: 'eb5', goalType: 'improve', cyclingType: 'road', planName: 'Keep improving' }, config: { id: 'ceb5', daysPerWeek: 3, weeks: 8, trainingTypes: ['outdoor'], availableDays: ['monday', 'wednesday', 'friday'], fitnessLevel: 'intermediate', startDate: '2026-04-06', longRideDay: 'wednesday' } },
  { name: 'EDGE (just-better): very short 2-week reset plan', goal: { id: 'eb6', goalType: 'improve', cyclingType: 'road', planName: 'Keep improving' }, config: { id: 'ceb6', daysPerWeek: 3, weeks: 2, trainingTypes: ['outdoor'], availableDays: ['tuesday', 'thursday', 'saturday'], fitnessLevel: 'beginner', startDate: '2026-04-06' } },
  { name: 'EDGE (just-better): 16-week beginner improvement arc', goal: { id: 'eb7', goalType: 'improve', cyclingType: 'road', planName: 'Keep improving' }, config: { id: 'ceb7', daysPerWeek: 3, weeks: 16, trainingTypes: ['outdoor'], availableDays: ['tuesday', 'thursday', 'sunday'], fitnessLevel: 'beginner', startDate: '2026-04-06' } },
  { name: 'EDGE (just-better): 3 rides + 2 strength atypical split', goal: { id: 'eb8', goalType: 'improve', cyclingType: 'road', planName: 'Keep improving' }, config: { id: 'ceb8', daysPerWeek: 5, weeks: 8, trainingTypes: ['outdoor', 'strength'], sessionCounts: { outdoor: 3, strength: 2 }, availableDays: ['monday', 'tuesday', 'wednesday', 'friday', 'saturday'], fitnessLevel: 'intermediate', startDate: '2026-04-06' } },
  { name: 'EDGE (just-better): indoor-only trainer 3 days', goal: { id: 'eb9', goalType: 'improve', cyclingType: 'road', planName: 'Keep improving' }, config: { id: 'ceb9', daysPerWeek: 3, weeks: 6, trainingTypes: ['indoor'], sessionCounts: { indoor: 3 }, availableDays: ['monday', 'wednesday', 'friday'], fitnessLevel: 'intermediate', startDate: '2026-04-06' } },
  { name: 'EDGE (just-better): gravel 4 days 10 weeks', goal: { id: 'eb10', goalType: 'improve', cyclingType: 'gravel', planName: 'Keep improving' }, config: { id: 'ceb10', daysPerWeek: 4, weeks: 10, trainingTypes: ['outdoor'], availableDays: ['monday', 'wednesday', 'friday', 'saturday'], fitnessLevel: 'intermediate', startDate: '2026-04-06' } },
  { name: 'EDGE (just-better): MTB beginner 3 days', goal: { id: 'eb11', goalType: 'improve', cyclingType: 'mtb', planName: 'Keep improving' }, config: { id: 'ceb11', daysPerWeek: 3, weeks: 8, trainingTypes: ['outdoor'], availableDays: ['tuesday', 'thursday', 'saturday'], fitnessLevel: 'beginner', startDate: '2026-04-06' } },
  { name: 'EDGE (just-better): advanced on 2 days/week minimal time', goal: { id: 'eb12', goalType: 'improve', cyclingType: 'road', planName: 'Keep improving' }, config: { id: 'eb12', daysPerWeek: 2, weeks: 6, trainingTypes: ['outdoor'], availableDays: ['wednesday', 'saturday'], fitnessLevel: 'advanced', startDate: '2026-04-06' } },
  { name: 'EDGE (just-better): 3-day plan starting mid-week Wed', goal: { id: 'eb13', goalType: 'improve', cyclingType: 'road', planName: 'Keep improving' }, config: { id: 'ceb13', daysPerWeek: 3, weeks: 6, trainingTypes: ['outdoor'], availableDays: ['monday', 'wednesday', 'saturday'], fitnessLevel: 'intermediate', startDate: '2026-04-08' } },

  // ── "Getting Started" edge cases — deliberately awkward beginner setups ──
  { name: 'EDGE (getting-started): 1 day/week couch-to-saddle', goal: { id: 'ebg1', goalType: 'beginner', cyclingType: 'road', planName: 'Get Into Cycling' }, config: { id: 'cebg1', daysPerWeek: 1, weeks: 6, trainingTypes: ['outdoor'], availableDays: ['saturday'], fitnessLevel: 'beginner', startDate: '2026-04-06' } },
  { name: 'EDGE (getting-started): shift worker Tue/Wed/Thu only', goal: { id: 'ebg2', goalType: 'beginner', cyclingType: 'road', planName: 'Get Into Cycling' }, config: { id: 'cebg2', daysPerWeek: 3, weeks: 8, trainingTypes: ['outdoor'], availableDays: ['tuesday', 'wednesday', 'thursday'], fitnessLevel: 'beginner', startDate: '2026-04-06' } },
  { name: 'EDGE (getting-started): weekends-only 2 days 10 weeks', goal: { id: 'ebg3', goalType: 'beginner', cyclingType: 'road', planName: 'Get Into Cycling' }, config: { id: 'cebg3', daysPerWeek: 2, weeks: 10, trainingTypes: ['outdoor'], availableDays: ['saturday', 'sunday'], fitnessLevel: 'beginner', startDate: '2026-04-06', longRideDay: 'sunday' } },
  { name: 'EDGE (getting-started): 16-week slow-burn commitment', goal: { id: 'ebg4', goalType: 'beginner', cyclingType: 'road', planName: 'Get Into Cycling' }, config: { id: 'cebg4', daysPerWeek: 3, weeks: 16, trainingTypes: ['outdoor'], availableDays: ['tuesday', 'thursday', 'saturday'], fitnessLevel: 'beginner', startDate: '2026-04-06' } },
  { name: 'EDGE (getting-started): 4-day morning commuter on e-bike', goal: { id: 'ebg5', goalType: 'beginner', cyclingType: 'ebike', planName: 'Get Into Cycling' }, config: { id: 'cebg5', daysPerWeek: 4, weeks: 8, trainingTypes: ['outdoor'], availableDays: ['monday', 'tuesday', 'wednesday', 'thursday'], fitnessLevel: 'beginner', startDate: '2026-04-06' } },
  { name: 'EDGE (getting-started): full programme outdoor+indoor+strength', goal: { id: 'ebg6', goalType: 'beginner', cyclingType: 'road', planName: 'Get Into Cycling' }, config: { id: 'cebg6', daysPerWeek: 5, weeks: 12, trainingTypes: ['outdoor', 'indoor', 'strength'], sessionCounts: { outdoor: 2, indoor: 2, strength: 1 }, availableDays: ['monday', 'tuesday', 'wednesday', 'friday', 'saturday'], fitnessLevel: 'beginner', startDate: '2026-04-06', longRideDay: 'saturday' } },
  { name: 'EDGE (getting-started): MTB absolute-beginner 3 days', goal: { id: 'ebg7', goalType: 'beginner', cyclingType: 'mtb', planName: 'Get Into Cycling' }, config: { id: 'cebg7', daysPerWeek: 3, weeks: 8, trainingTypes: ['outdoor'], availableDays: ['tuesday', 'thursday', 'sunday'], fitnessLevel: 'beginner', startDate: '2026-04-06' } },
  { name: 'EDGE (getting-started): long ride on Friday (unusual)', goal: { id: 'ebg8', goalType: 'beginner', cyclingType: 'road', planName: 'Get Into Cycling' }, config: { id: 'cebg8', daysPerWeek: 3, weeks: 8, trainingTypes: ['outdoor'], availableDays: ['monday', 'wednesday', 'friday'], fitnessLevel: 'beginner', startDate: '2026-04-06', longRideDay: 'friday' } },
  { name: 'EDGE (getting-started): 3-week short trial plan', goal: { id: 'ebg9', goalType: 'beginner', cyclingType: 'road', planName: 'Get Into Cycling' }, config: { id: 'cebg9', daysPerWeek: 2, weeks: 3, trainingTypes: ['outdoor'], availableDays: ['wednesday', 'saturday'], fitnessLevel: 'beginner', startDate: '2026-04-06' } },
  { name: 'EDGE (getting-started): 2 days 4 weeks e-bike returner', goal: { id: 'ebg10', goalType: 'beginner', cyclingType: 'ebike', planName: 'Get Into Cycling' }, config: { id: 'cebg10', daysPerWeek: 2, weeks: 4, trainingTypes: ['outdoor'], availableDays: ['wednesday', 'saturday'], fitnessLevel: 'beginner', startDate: '2026-04-06' } },
  { name: 'EDGE (getting-started): gravel 3 days 10 weeks', goal: { id: 'ebg11', goalType: 'beginner', cyclingType: 'gravel', planName: 'Get Into Cycling' }, config: { id: 'cebg11', daysPerWeek: 3, weeks: 10, trainingTypes: ['outdoor'], availableDays: ['tuesday', 'thursday', 'sunday'], fitnessLevel: 'beginner', startDate: '2026-04-06' } },
  { name: 'EDGE (getting-started): 14-week standard couch-to-ride', goal: { id: 'ebg12', goalType: 'beginner', cyclingType: 'road', planName: 'Get Into Cycling' }, config: { id: 'cebg12', daysPerWeek: 3, weeks: 14, trainingTypes: ['outdoor'], availableDays: ['tuesday', 'thursday', 'saturday'], fitnessLevel: 'beginner', startDate: '2026-04-06' } },
  { name: 'EDGE (getting-started): mid-month start date 15th', goal: { id: 'ebg13', goalType: 'beginner', cyclingType: 'road', planName: 'Get Into Cycling' }, config: { id: 'cebg13', daysPerWeek: 3, weeks: 8, trainingTypes: ['outdoor'], availableDays: ['monday', 'wednesday', 'saturday'], fitnessLevel: 'beginner', startDate: '2026-04-15' } },

  // ── Beginner programme with explicit target distance — 3 tiers ──────────
  // These cover the three options on BeginnerProgramScreen: 25 km "habit",
  // 50 km "endurance", 100 km "century". Each plan MUST build to the target,
  // culminating in a graduation ride within 10 km of the goal. Locks in the
  // fix for "user picked 100 km but plan peaked at 27 km".
  { name: 'BEGINNER TARGET: 25 km habit goal, 12 weeks', goal: { id: 'bt1', goalType: 'beginner', cyclingType: 'road', targetDistance: 25, planName: 'Get Into Cycling' }, config: { id: 'cbt1', daysPerWeek: 3, weeks: 12, trainingTypes: ['outdoor'], availableDays: ['tuesday', 'thursday', 'saturday'], fitnessLevel: 'beginner', startDate: '2026-04-06', longRideDay: 'saturday' } },
  { name: 'BEGINNER TARGET: 50 km endurance goal, 12 weeks', goal: { id: 'bt2', goalType: 'beginner', cyclingType: 'road', targetDistance: 50, planName: 'Get Into Cycling' }, config: { id: 'cbt2', daysPerWeek: 3, weeks: 12, trainingTypes: ['outdoor'], availableDays: ['tuesday', 'thursday', 'saturday'], fitnessLevel: 'beginner', startDate: '2026-04-06', longRideDay: 'saturday' } },
  { name: 'BEGINNER TARGET: 100 km century goal, 12 weeks', goal: { id: 'bt3', goalType: 'beginner', cyclingType: 'road', targetDistance: 100, planName: 'Get Into Cycling' }, config: { id: 'cbt3', daysPerWeek: 3, weeks: 12, trainingTypes: ['outdoor'], availableDays: ['tuesday', 'thursday', 'saturday'], fitnessLevel: 'beginner', startDate: '2026-04-06', longRideDay: 'saturday' } },
  { name: 'BEGINNER TARGET: 100 km century, 4 days/week including strength', goal: { id: 'bt4', goalType: 'beginner', cyclingType: 'road', targetDistance: 100, planName: 'Get Into Cycling' }, config: { id: 'cbt4', daysPerWeek: 4, weeks: 12, trainingTypes: ['outdoor', 'strength'], sessionCounts: { outdoor: 3, strength: 1 }, availableDays: ['tuesday', 'wednesday', 'thursday', 'saturday'], fitnessLevel: 'beginner', startDate: '2026-04-06', longRideDay: 'saturday' } },
  { name: 'BEGINNER TARGET: 50 km on 2 days/week', goal: { id: 'bt5', goalType: 'beginner', cyclingType: 'road', targetDistance: 50, planName: 'Get Into Cycling' }, config: { id: 'cbt5', daysPerWeek: 2, weeks: 12, trainingTypes: ['outdoor'], availableDays: ['wednesday', 'saturday'], fitnessLevel: 'beginner', startDate: '2026-04-06', longRideDay: 'saturday' } },
  { name: 'BEGINNER TARGET: 100 km e-bike century 12 weeks', goal: { id: 'bt6', goalType: 'beginner', cyclingType: 'ebike', targetDistance: 100, planName: 'Get Into Cycling' }, config: { id: 'cbt6', daysPerWeek: 3, weeks: 12, trainingTypes: ['outdoor'], availableDays: ['tuesday', 'thursday', 'saturday'], fitnessLevel: 'beginner', startDate: '2026-04-06', longRideDay: 'saturday' } },
  { name: 'BEGINNER TARGET: 25 km, 8 weeks (short programme)', goal: { id: 'bt7', goalType: 'beginner', cyclingType: 'road', targetDistance: 25, planName: 'Get Into Cycling' }, config: { id: 'cbt7', daysPerWeek: 3, weeks: 8, trainingTypes: ['outdoor'], availableDays: ['tuesday', 'thursday', 'saturday'], fitnessLevel: 'beginner', startDate: '2026-04-06', longRideDay: 'saturday' } },
];

export const EDIT_SCENARIOS = [
  { name: 'Make plan easier — reduce volume', type: 'plan-edit', instruction: "Make the plan easier — I'm feeling tired. Reduce distances and effort levels.", scope: 'remaining', currentWeek: 2 },
  { name: 'Make plan harder — increase intensity', type: 'plan-edit', instruction: 'I want more of a challenge. Add more interval sessions and increase distances.', scope: 'remaining', currentWeek: 3 },
  { name: 'Edit single activity — make shorter', type: 'activity-edit', instruction: 'Make this session 30 minutes shorter' },
  { name: 'Edit single activity — ask a question (no modify)', type: 'activity-edit', instruction: 'Why is this session here? What am I trying to achieve with it?' },
  { name: 'Edit plan — add strength on Wednesday', type: 'plan-edit', instruction: 'Add a 45-minute strength/gym session every Wednesday for the remaining weeks.', scope: 'remaining', currentWeek: 2 },
  { name: 'Edit plan — move long ride to Saturday', type: 'plan-edit', instruction: 'Move my long ride each week to Saturday. I prefer doing my longest ride on Saturdays.', scope: 'remaining', currentWeek: 2 },
  { name: 'Edit single activity — swap to indoor trainer', type: 'activity-edit', instruction: "I can't ride outside today because of rain. Convert this to an indoor trainer session with the same effort level but slightly shorter." },
  { name: 'Edit plan — add recovery after hard days', type: 'plan-edit', instruction: 'After every interval or hard effort ride, please schedule a short easy recovery spin the next day (30 minutes, easy effort).', scope: 'remaining', currentWeek: 2 },
];
