/**
 * ActivityFeedbackSheet — bottom sheet shown when the rider marks a session
 * complete. Captures three structured signals + an optional note that flow
 * into the next weekly check-in so the coach has real data on how each
 * ride felt rather than relying on free-text memory.
 *
 * Two-phase UX:
 *   1. FORM phase — effort / feel / optional note. Save fires onSave and
 *      transitions to:
 *   2. REACTION phase — a single coach-voiced reaction generated by
 *      Haiku via fetchPostRideReaction. The rider can either tap "Done"
 *      to dismiss, or "Chat with <coach>" to jump into CoachChatScreen
 *      with the activity + feedback + reaction seeded as opening
 *      context. This closes the loop on the moment ("you said way too
 *      hard — got it") without committing to plan changes; those still
 *      happen in the weekly check-in.
 *
 * Why now:
 *   - The weekly check-in used to ask "any sessions feel hard?" days after
 *     the fact. Riders forgot the specifics. By prompting at the moment
 *     the session is marked done, we capture truth (hot, fresh, specific)
 *     not reconstruction.
 *   - Three structured fields (effort, feel, note) are the smallest set
 *     that's still useful for plan adjustments — anything more becomes a
 *     form, anything less is just a checkbox.
 *
 * Layout matches the rest of Etapa's bottom sheets (RescheduleCheckInSheet,
 * UnavailabilitySheet, BikeSwapModal): black backdrop, surface card with
 * grab-handle, sticky title, KeyboardAvoidingView so the textarea is
 * visible when the keyboard opens.
 *
 * Props:
 *   visible           — boolean, controls Modal mount
 *   activity          — the activity being reviewed (used for the meta line)
 *   saving            — boolean. True while the parent is still persisting
 *                       the activity-completion flag (markActivityComplete
 *                       round-trip in flight). When true the sheet renders
 *                       a small "Saving your ride…" banner above the form
 *                       and disables the Save button so the rider can't
 *                       race the activity-done save with the feedback save.
 *                       The form itself stays visible and interactive so
 *                       they can start filling it in while the round-trip
 *                       lands.
 *   onSave            — ({ effort, rpe, feel, note }) => void
 *   onSkip            — () => void  — completion stands, no feedback recorded
 *   onClose           — () => void  — backdrop tap; treated the same as Skip
 *   onChatWithCoach   — ({ activity, feedback, reaction }) => void
 *                       Tapping the "Chat with <coach>" button after the
 *                       reaction lands. Parent navigates to CoachChatScreen
 *                       with these seeded as opening context.
 *
 * State persistence: the parent owns it. The sheet resets local state
 * whenever `visible` flips to false so a subsequent open is a clean
 * slate.
 */
import React, { useEffect, useRef, useState } from 'react';
import {
  View, Text, TouchableOpacity, Modal, StyleSheet, TextInput,
  KeyboardAvoidingView, Platform, ScrollView, ActivityIndicator,
} from 'react-native';
import { MaterialCommunityIcons } from '@expo/vector-icons';
import { colors, fontFamily } from '../theme';
import { fetchPostRideReaction } from '../services/llmPlanService';

const FF = fontFamily;

// Effort segments. The label maps to a coarse RPE bucket so the coach
// prompt can reason in numbers without making the rider think in numbers.
// We keep the rider-facing label plain English and the RPE as a derived
// value the analytics + check-in pipeline both consume.
const EFFORT_OPTIONS = [
  { key: 'way_too_easy', label: 'Way too easy', rpe: 2 },
  { key: 'easy',          label: 'Easy',         rpe: 4 },
  { key: 'just_right',    label: 'Just right',   rpe: 6 },
  { key: 'hard',          label: 'Hard',         rpe: 8 },
  { key: 'way_too_hard',  label: 'Way too hard', rpe: 10 },
];

const FEEL_OPTIONS = [
  { key: 'strong', label: 'Strong' },
  { key: 'ok',     label: 'OK' },
  { key: 'off',    label: 'Off' },
];

// Build the activity meta line used under the title — e.g. "Saturday Long
// Ride · 65 km". We don't need the full activity, just the bits the rider
// will recognise. Falls back gracefully if any single field is absent.
function buildMetaLine(activity) {
  if (!activity) return '';
  const bits = [activity.title || 'Ride'];
  if (activity.distanceKm) bits.push(`${Math.round(activity.distanceKm)} km`);
  else if (activity.durationMins) bits.push(`${activity.durationMins} min`);
  return bits.join(' \u00B7 ');
}

export default function ActivityFeedbackSheet({
  visible, activity, saving = false, onSave, onSkip, onClose, onChatWithCoach,
}) {
  // Local form state — parent owns nothing here. We reset on close so the
  // next session's sheet doesn't inherit a stale answer.
  const [effort, setEffort] = useState(null); // 'way_too_easy' | ...
  const [feel, setFeel] = useState(null);     // 'strong' | 'ok' | 'off'
  const [note, setNote] = useState('');

  // Two-phase state — 'form' until Save, then 'loading' while Haiku
  // generates the coach reaction, then 'reaction' once it lands. We keep
  // the saved feedback object around in a ref so the Chat handoff has
  // exactly what was persisted.
  const [phase, setPhase] = useState('form'); // form | loading | reaction
  const [reaction, setReaction] = useState(null); // { message, coachName, coachId } | null
  const savedFeedbackRef = useRef(null);

  useEffect(() => {
    if (!visible) {
      setEffort(null);
      setFeel(null);
      setNote('');
      setPhase('form');
      setReaction(null);
      savedFeedbackRef.current = null;
    }
  }, [visible]);

  const handleSave = async () => {
    // We allow Save even when the rider hasn't picked an effort or feel —
    // the floor is "this rider tapped Save, even an empty note has signal
    // (they cared enough to acknowledge the prompt)." If the caller
    // wants to enforce a minimum, they can pre-validate; the sheet
    // doesn't impose it.
    const opt = EFFORT_OPTIONS.find(o => o.key === effort);
    const feedback = {
      effort: effort || null,
      rpe: opt ? opt.rpe : null,
      feel: feel || null,
      note: note.trim() || null,
    };
    savedFeedbackRef.current = feedback;
    onSave?.(feedback);

    // Transition to loading phase and fire the Haiku call. We do not
    // block onSave — persistence already happened above. If the network
    // is offline or the call fails we still close out cleanly without
    // showing a scary error: the rider just sees the sheet dismiss
    // (parent already toasted "saved").
    setPhase('loading');
    try {
      const r = await fetchPostRideReaction(activity, feedback);
      if (r && r.message) {
        setReaction(r);
        setPhase('reaction');
      } else {
        // Quietly close — parent's toast covers the "saved" signal.
        onClose?.();
      }
    } catch {
      onClose?.();
    }
  };

  const handleChatWithCoach = () => {
    onChatWithCoach?.({
      activity,
      feedback: savedFeedbackRef.current,
      reaction,
    });
  };

  if (!visible) return null;

  return (
    <Modal
      visible
      transparent
      animationType="slide"
      onRequestClose={onClose}
      statusBarTranslucent
    >
      <KeyboardAvoidingView
        behavior={Platform.OS === 'ios' ? 'padding' : 'height'}
        style={s.kbWrap}
      >
        <TouchableOpacity style={s.backdrop} onPress={onClose} activeOpacity={1} />
        <View style={s.sheet}>
          <View style={s.grab} />

          {/* ScrollView so the textarea stays reachable on small phones
              when the keyboard opens. Scroll-on-drag dismisses the
              keyboard gently — same pattern as the organised-ride modal
              in WeekViewScreen. */}
          <ScrollView
            keyboardDismissMode="on-drag"
            keyboardShouldPersistTaps="handled"
            showsVerticalScrollIndicator={false}
            contentContainerStyle={s.scrollContent}
          >
            <View style={s.headerRow}>
              <View style={{ flex: 1 }}>
                <Text style={s.title}>
                  {phase === 'form' ? 'How did it go?'
                    : phase === 'loading' ? 'Saving…'
                    : `${reaction?.coachName || 'Coach'} says`}
                </Text>
                {phase === 'form' ? (
                  <Text style={s.subtitle}>Your coach will use this in your next check-in</Text>
                ) : null}
                <Text style={s.meta}>{buildMetaLine(activity)}</Text>
              </View>
              <TouchableOpacity onPress={onClose} hitSlop={HIT}>
                <MaterialCommunityIcons name="close" size={20} color={colors.textMid} />
              </TouchableOpacity>
            </View>

            {/* ── Loading phase ── Haiku is fast (sub-second target) so
                this should usually flash, but we show an honest spinner
                + caption rather than a skeleton — riders who have a
                slow connection deserve clarity over flair. */}
            {phase === 'loading' ? (
              <View style={s.loadingBlock}>
                <ActivityIndicator color={colors.primary} />
                <Text style={s.loadingText}>Talking to your coach…</Text>
              </View>
            ) : null}

            {/* ── Reaction phase ── single coach message + two paths
                forward: dismiss with Done, or jump into CoachChatScreen
                with the reaction seeded as opening context. We don't
                offer "regenerate" — the response is one-shot by design.
                If the rider wants more, that's the chat. */}
            {phase === 'reaction' && reaction ? (
              <View style={s.reactionBlock}>
                <View style={s.reactionBubble}>
                  <Text style={s.reactionText}>{reaction.message}</Text>
                </View>
                <Text style={s.reactionFootnote}>
                  Plan changes happen in the weekly check-in. For more, jump into chat.
                </Text>
                <TouchableOpacity
                  style={s.saveBtn}
                  onPress={handleChatWithCoach}
                  activeOpacity={0.85}
                  accessibilityLabel={`Chat with ${reaction.coachName || 'coach'}`}
                >
                  <Text style={s.saveBtnText}>{`Chat with ${reaction.coachName || 'your coach'}`}</Text>
                </TouchableOpacity>
                <TouchableOpacity
                  style={s.skipBtn}
                  onPress={onClose}
                  activeOpacity={0.7}
                  accessibilityLabel="Done"
                >
                  <Text style={s.skipBtnText}>Done</Text>
                </TouchableOpacity>
              </View>
            ) : null}

            {/* ── Form phase ── original effort / feel / note. Hidden as
                soon as Save is tapped so the rider doesn't see their
                inputs ghosted under the loading spinner. */}
            {phase === 'form' ? (
              <>
            {/* ── Saving banner ── visible only while the parent is still
                persisting the activity-completion flag (the round-trip
                fired when the rider tapped the check circle to mark the
                session done). The popup opens optimistically so the
                rider sees something the moment they tap, but the Save
                button stays disabled until the activity-done save lands
                — otherwise the feedback save could hit the server
                before its activity row is marked completed. */}
            {saving ? (
              <View style={s.savingBanner} accessibilityRole="alert">
                <ActivityIndicator size="small" color={colors.primary} />
                <Text style={s.savingBannerText}>Saving your ride…</Text>
              </View>
            ) : null}

            {/* ── Effort ── five horizontal segments. We render them as
                equal-width pills inside a row so the chosen one is
                obvious (pink fill) and the others stay quiet. */}
            <Text style={s.qLabel}>Effort</Text>
            <View style={s.effortRow}>
              {EFFORT_OPTIONS.map(opt => {
                const selected = effort === opt.key;
                return (
                  <TouchableOpacity
                    key={opt.key}
                    style={[s.effortSeg, selected && s.effortSegOn]}
                    onPress={() => setEffort(opt.key)}
                    activeOpacity={0.7}
                    accessibilityRole="button"
                    accessibilityState={{ selected }}
                  >
                    <Text style={[s.effortSegText, selected && s.effortSegTextOn]}>{opt.label}</Text>
                  </TouchableOpacity>
                );
              })}
            </View>

            {/* ── Feel ── three larger buttons. The dichotomy strong/ok/off
                is deliberately coarse — fine enough to spot a pattern
                ("legs were off all week") without asking the rider to
                introspect. */}
            <Text style={[s.qLabel, { marginTop: 18 }]}>How did it feel?</Text>
            <View style={s.feelRow}>
              {FEEL_OPTIONS.map(opt => {
                const selected = feel === opt.key;
                return (
                  <TouchableOpacity
                    key={opt.key}
                    style={[s.feelBtn, selected && s.feelBtnOn]}
                    onPress={() => setFeel(opt.key)}
                    activeOpacity={0.7}
                    accessibilityRole="button"
                    accessibilityState={{ selected }}
                  >
                    <Text style={[s.feelText, selected && s.feelTextOn]}>{opt.label}</Text>
                  </TouchableOpacity>
                );
              })}
            </View>

            {/* ── Optional note ── two-line textarea. Placeholder primes
                the rider with concrete examples so they answer in
                plain words rather than the formal tone the old
                check-in screen pulled out. */}
            <Text style={[s.qLabel, { marginTop: 18 }]}>Anything to add? (optional)</Text>
            <TextInput
              style={s.noteInput}
              placeholder="legs heavy on the climbs, found a great new road"
              placeholderTextColor={colors.textFaint}
              value={note}
              onChangeText={setNote}
              multiline
              maxLength={300}
            />

            <Text style={s.footerCaption}>This goes straight to your coach</Text>

            <TouchableOpacity
              style={[s.saveBtn, saving && s.saveBtnDisabled]}
              onPress={handleSave}
              activeOpacity={saving ? 1 : 0.85}
              disabled={saving}
              accessibilityLabel={saving ? 'Saving your ride…' : 'Save feedback'}
              accessibilityState={{ disabled: saving }}
            >
              <Text style={s.saveBtnText}>{saving ? 'Saving your ride…' : 'Save'}</Text>
            </TouchableOpacity>

            <TouchableOpacity
              style={s.skipBtn}
              onPress={onSkip}
              activeOpacity={0.7}
              accessibilityLabel="Skip — keep completion, no feedback"
            >
              <Text style={s.skipBtnText}>Skip</Text>
            </TouchableOpacity>
              </>
            ) : null}
          </ScrollView>
        </View>
      </KeyboardAvoidingView>
    </Modal>
  );
}

const HIT = { top: 12, bottom: 12, left: 12, right: 12 };

const s = StyleSheet.create({
  kbWrap: { flex: 1, justifyContent: 'flex-end' },
  backdrop: { position: 'absolute', top: 0, bottom: 0, left: 0, right: 0, backgroundColor: 'rgba(0,0,0,0.6)' },

  sheet: {
    backgroundColor: colors.surface,
    borderTopLeftRadius: 22, borderTopRightRadius: 22,
    paddingTop: 6, paddingBottom: 16,
    borderTopWidth: 0.5, borderColor: colors.border,
    maxHeight: '90%',
  },
  grab: { width: 40, height: 4, borderRadius: 2, backgroundColor: colors.border, alignSelf: 'center', marginBottom: 6 },

  scrollContent: { paddingHorizontal: 18, paddingBottom: 24 },

  headerRow: {
    flexDirection: 'row', alignItems: 'flex-start', gap: 12,
    paddingTop: 6, paddingBottom: 14,
    borderBottomWidth: 0.5, borderBottomColor: colors.borderLight,
    marginBottom: 16,
  },
  title: { fontSize: 18, fontWeight: '600', color: colors.text, fontFamily: FF.semibold, marginBottom: 4 },
  subtitle: { fontSize: 12, color: colors.textMid, fontFamily: FF.regular, lineHeight: 17 },
  meta: { fontSize: 12, color: colors.textMuted, fontFamily: FF.regular, marginTop: 6 },

  qLabel: { fontSize: 13, fontWeight: '600', color: colors.text, fontFamily: FF.semibold, marginBottom: 10 },

  // Loading phase — spinner + caption while Haiku generates the
  // post-ride reaction. Sub-second target so this should usually flash;
  // copy is honest rather than coy ("Talking to your coach…" not
  // "Doing its thing…").
  loadingBlock: {
    paddingVertical: 28, alignItems: 'center', gap: 12,
  },
  loadingText: { fontSize: 13, color: colors.textMid, fontFamily: FF.regular },

  // Reaction phase — pink-tinted bubble with the coach's one-shot
  // response, a footnote making the boundary clear (plan changes still
  // happen in the weekly check-in), then chat / done CTAs.
  reactionBlock: { paddingTop: 4 },
  reactionBubble: {
    backgroundColor: colors.primary + '14',
    borderLeftWidth: 2, borderLeftColor: colors.primary,
    borderRadius: 12, padding: 14,
  },
  reactionText: {
    fontSize: 14, color: colors.text, fontFamily: FF.regular, lineHeight: 21,
  },
  reactionFootnote: {
    fontSize: 11, color: colors.textMuted, fontFamily: FF.regular,
    marginTop: 12, lineHeight: 15,
  },

  // Effort — five equal segments side by side. Smaller text than the
  // feel row because labels can be long ("Way too easy" / "Way too
  // hard"). centred so the segment looks balanced when selected.
  effortRow: { flexDirection: 'row', gap: 6 },
  effortSeg: {
    flex: 1, paddingVertical: 10, paddingHorizontal: 4,
    borderRadius: 10, backgroundColor: colors.surfaceLight,
    borderWidth: 0.5, borderColor: colors.border,
    alignItems: 'center', justifyContent: 'center',
    minHeight: 44,
  },
  effortSegOn: { backgroundColor: colors.primary + '22', borderColor: colors.primary, borderWidth: 1.5 },
  effortSegText: { fontSize: 11, color: colors.textMid, fontFamily: FF.regular, textAlign: 'center', lineHeight: 14 },
  effortSegTextOn: { color: colors.text, fontWeight: '600', fontFamily: FF.semibold },

  // Feel — three roomier buttons. Coarse on purpose.
  feelRow: { flexDirection: 'row', gap: 8 },
  feelBtn: {
    flex: 1, paddingVertical: 14, borderRadius: 10,
    backgroundColor: colors.surfaceLight,
    borderWidth: 0.5, borderColor: colors.border,
    alignItems: 'center',
  },
  feelBtnOn: { backgroundColor: colors.primary + '22', borderColor: colors.primary, borderWidth: 1.5 },
  feelText: { fontSize: 13, color: colors.textMid, fontFamily: FF.regular },
  feelTextOn: { color: colors.text, fontWeight: '600', fontFamily: FF.semibold },

  noteInput: {
    backgroundColor: colors.surfaceLight,
    borderWidth: 0.5, borderColor: colors.border, borderRadius: 12,
    paddingHorizontal: 12, paddingVertical: 12,
    fontSize: 14, color: colors.text, fontFamily: FF.regular,
    minHeight: 60, textAlignVertical: 'top',
  },

  footerCaption: {
    fontSize: 11, color: colors.textMuted, fontFamily: FF.regular,
    marginTop: 12, marginBottom: 4,
  },

  saveBtn: {
    backgroundColor: colors.primary, paddingVertical: 14,
    borderRadius: 12, alignItems: 'center', marginTop: 14,
  },
  // Disabled state while the activity-completion save is mid-flight.
  // Lower opacity reads as "not yet" rather than "broken".
  saveBtnDisabled: { opacity: 0.5 },
  saveBtnText: { color: '#fff', fontSize: 14, fontWeight: '600', fontFamily: FF.semibold },

  // ── Saving banner (form phase, while activity-done save is in flight) ──
  // Pink-tinted strip at the top of the form. Spinner + plain English so
  // the rider knows their tap registered and the round-trip is still
  // resolving. Disappears as soon as the parent sets saving=false.
  savingBanner: {
    flexDirection: 'row', alignItems: 'center', gap: 10,
    paddingVertical: 10, paddingHorizontal: 12,
    borderRadius: 10,
    backgroundColor: colors.primary + '14',
    borderWidth: 0.5, borderColor: colors.primary + '50',
    marginBottom: 14,
  },
  savingBannerText: {
    flex: 1, fontSize: 12, color: colors.text, fontFamily: FF.regular,
  },

  skipBtn: {
    paddingVertical: 13, borderRadius: 12,
    borderWidth: 0.5, borderColor: colors.border,
    alignItems: 'center', marginTop: 8,
  },
  skipBtnText: { color: colors.textMid, fontSize: 13, fontFamily: FF.regular },
});
