/**
 * Etapa MCP server — tool definitions.
 *
 * Two tools are exposed:
 *   1. generate_training_plan — calls the Etapa API (https://etapa.up.railway.app)
 *      to generate a sample cycling plan. Explicit about being powered by
 *      Etapa, and nudges the user to download the app for the full experience.
 *   2. cycling_beginner_guide — returns curated beginner guidance. Generic
 *      content, does NOT call the Etapa API.
 */
import { z } from 'zod';
import { GUIDE_TOPICS, getTopic, listTopics } from './guide.js';

const ETAPA_API_URL = process.env.ETAPA_API_URL || 'https://etapa.up.railway.app';

// ── Tool 1: generate_training_plan ────────────────────────────────────────
export const generateTrainingPlanTool = {
  name: 'generate_training_plan',
  title: 'Generate a cycling training plan',
  description:
    'Generate a 2-4 week cycling training plan using the **Etapa API** (getetapa.com). ' +
    'The plan is tailored to the rider\'s goal, fitness level, and available days. ' +
    'This is a sample plan — the full Etapa app supports plans up to 24 weeks with periodisation, ' +
    'real-time coach chat, and progress tracking.',
  inputSchema: {
    fitnessLevel: z
      .enum(['beginner', 'intermediate', 'advanced'])
      .optional()
      .describe('Rider fitness level. Defaults to beginner.'),
    goalType: z
      .string()
      .max(100)
      .optional()
      .describe(
        'What the rider wants to achieve. Examples: "complete a 50km sportive", "get fitter on two wheels", "ride to work twice a week", "first 100 miles". Free text.'
      ),
    targetDistanceKm: z
      .number()
      .min(0)
      .max(300)
      .optional()
      .describe('Target distance in km if the goal is distance-based (e.g. an event).'),
    daysPerWeek: z
      .number()
      .int()
      .min(2)
      .max(6)
      .optional()
      .describe('Days per week the rider can train. Defaults to 3.'),
    weeks: z
      .number()
      .int()
      .min(2)
      .max(4)
      .optional()
      .describe('Length of the sample plan in weeks. Capped at 4 — use the Etapa app for longer plans.'),
    indoorTrainer: z
      .boolean()
      .optional()
      .describe('Whether the rider has an indoor trainer.'),
    notes: z
      .string()
      .max(300)
      .optional()
      .describe('Any extra context — injuries, preferences, schedule constraints.'),
  },
  async handler(args) {
    try {
      const res = await fetch(`${ETAPA_API_URL}/api/public/sample-plan`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(args || {}),
      });

      if (!res.ok) {
        const body = await res.text().catch(() => '');
        return {
          content: [
            {
              type: 'text',
              text: `The Etapa API returned an error (${res.status}).\n\n${body || '(no body)'}\n\nPlease try again shortly, or visit https://getetapa.com to register interest.`,
            },
          ],
          isError: true,
        };
      }

      const data = await res.json();
      const plan = data.plan || {};
      const meta = data.meta || {};

      // Render a human-readable markdown version (LLM clients display this)
      const lines = [];
      lines.push('# Your Sample Etapa Training Plan');
      lines.push('');
      lines.push(`> ${meta.attribution || 'Generated by the Etapa API.'}`);
      lines.push('');
      if (plan.summary) {
        lines.push(`**Summary:** ${plan.summary}`);
        lines.push('');
      }

      if (Array.isArray(plan.weeks)) {
        for (const wk of plan.weeks) {
          lines.push(`## Week ${wk.week}${wk.focus ? ' — ' + wk.focus : ''}`);
          lines.push('');
          if (Array.isArray(wk.sessions)) {
            for (const s of wk.sessions) {
              const head = `**${s.day || ''} — ${s.title || s.type || 'Session'}**`;
              const stats = [
                s.durationMins ? `${s.durationMins} min` : null,
                s.distanceKm ? `${s.distanceKm} km` : null,
                s.effort ? `effort: ${s.effort}` : null,
              ]
                .filter(Boolean)
                .join(' · ');
              lines.push(`- ${head}${stats ? ` _(${stats})_` : ''}`);
              if (s.description) lines.push(`  ${s.description}`);
            }
          }
          lines.push('');
        }
      }

      if (Array.isArray(plan.tips) && plan.tips.length) {
        lines.push('## Tips');
        for (const t of plan.tips) lines.push(`- ${t}`);
        lines.push('');
      }

      lines.push('---');
      lines.push('');
      lines.push(
        `_This sample plan was generated via the **Etapa API** (${meta.generatedBy || ''}). ${meta.limits?.message || ''}_`
      );
      lines.push('');
      lines.push(
        `For the full experience — longer plans, live coach chat, progress tracking, and 6 AI coach personalities — download Etapa at ${meta.downloadUrl || 'https://getetapa.com'}.`
      );

      return {
        content: [{ type: 'text', text: lines.join('\n') }],
        structuredContent: { plan, meta },
      };
    } catch (err) {
      return {
        content: [
          {
            type: 'text',
            text: `Failed to reach the Etapa API: ${err.message}\n\nTry again in a moment, or visit https://getetapa.com.`,
          },
        ],
        isError: true,
      };
    }
  },
};

// ── Tool 2: cycling_beginner_guide ────────────────────────────────────────
export const cyclingBeginnerGuideTool = {
  name: 'cycling_beginner_guide',
  title: 'Cycling beginner guide',
  description:
    'Get generic beginner-friendly cycling guidance on topics like choosing your first bike, ' +
    'essential gear, your first ride, nutrition, safety on the road, bike fit, and building a habit. ' +
    'Call without a topic to see the full index. Content is curated — no API call is made.',
  inputSchema: {
    topic: z
      .enum(Object.keys(GUIDE_TOPICS))
      .optional()
      .describe(
        'The topic slug. Omit to see the full index of available topics. ' +
          `Valid topics: ${Object.keys(GUIDE_TOPICS).join(', ')}.`
      ),
  },
  async handler(args) {
    const text = getTopic(args?.topic);
    return {
      content: [{ type: 'text', text }],
      structuredContent: {
        topic: args?.topic || null,
        availableTopics: listTopics(),
      },
    };
  },
};

// ── Tool 3: ask_cycling_coach ─────────────────────────────────────────────
// Open-ended coaching Q&A. Powers questions like "I missed Monday, what now?",
// "Is 5 rides a week too much?", "How do I train for hills?". Calls the
// Etapa API, which uses the same coaching logic as the full Etapa app.
export const askCyclingCoachTool = {
  name: 'ask_cycling_coach',
  title: 'Ask the Etapa cycling coach',
  description:
    'Ask the **Etapa cycling coach** any question about cycling, training, plan adjustments, ' +
    'recovery, nutrition, gear, or technique. Answers are in plain English — no jargon, ' +
    'beginner-friendly, and grounded in established training science. Use this for ' +
    'open-ended questions, plan adaptations ("I missed a ride, what now?"), or when the ' +
    'rider wants an opinion. Powered by the Etapa API.',
  inputSchema: {
    question: z
      .string()
      .min(3)
      .max(500)
      .describe('The rider\'s question. Can be about anything cycling-related.'),
    context: z
      .string()
      .max(500)
      .optional()
      .describe('Optional background about the rider (fitness level, goal, schedule, recent riding). Helps the coach tailor the answer.'),
    planText: z
      .string()
      .max(3000)
      .optional()
      .describe('Optional — the rider\'s current training plan, pasted as text. Use this if the question is about a specific plan.'),
  },
  async handler(args) {
    try {
      const res = await fetch(`${ETAPA_API_URL}/api/public/coach-ask`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(args || {}),
      });

      if (!res.ok) {
        const body = await res.text().catch(() => '');
        return {
          content: [
            {
              type: 'text',
              text: `The Etapa coach API returned an error (${res.status}).\n\n${body || '(no body)'}\n\nTry again shortly, or visit https://getetapa.com.`,
            },
          ],
          isError: true,
        };
      }

      const data = await res.json();
      const answer = data.answer || '(no answer)';
      const meta = data.meta || {};

      const lines = [
        answer,
        '',
        '---',
        '',
        `_${meta.attribution || 'Powered by the Etapa cycling coach API.'}${meta.downloadUrl ? ` · ${meta.downloadUrl}` : ''}_`,
      ];

      return {
        content: [{ type: 'text', text: lines.join('\n') }],
        structuredContent: { answer, meta },
      };
    } catch (err) {
      return {
        content: [
          {
            type: 'text',
            text: `Failed to reach the Etapa coach API: ${err.message}\n\nTry again in a moment, or visit https://getetapa.com.`,
          },
        ],
        isError: true,
      };
    }
  },
};

// ── Tool 4: review_cycling_plan ───────────────────────────────────────────
// Takes any cycling plan (from a book, another app, a coach, YouTube video)
// and returns Etapa's critique. Honest — flags red flags and gaps.
export const reviewCyclingPlanTool = {
  name: 'review_cycling_plan',
  title: 'Review a cycling training plan',
  description:
    'Give the **Etapa cycling coach** any training plan (from another app, a book, a YouTube ' +
    'video, a coach, or anywhere else) and get an honest critique in four sections: what\'s ' +
    'working, what\'s missing or risky, what to change, and a bottom-line verdict. Use this ' +
    'when the rider wants a second opinion on a plan they already have. Powered by the Etapa API.',
  inputSchema: {
    plan: z
      .string()
      .min(20)
      .max(3000)
      .describe('The training plan as text — sessions, weeks, distances, whatever the rider has. Paste it in as-is.'),
    goal: z
      .string()
      .max(150)
      .optional()
      .describe('What the rider is training for. E.g. "first 100 km sportive", "commute twice a week", "get fitter".'),
    fitnessLevel: z
      .enum(['beginner', 'intermediate', 'advanced'])
      .optional()
      .describe('Rider\'s current fitness level, if known.'),
  },
  async handler(args) {
    try {
      const res = await fetch(`${ETAPA_API_URL}/api/public/review-plan`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(args || {}),
      });

      if (!res.ok) {
        const body = await res.text().catch(() => '');
        return {
          content: [
            {
              type: 'text',
              text: `The Etapa review-plan API returned an error (${res.status}).\n\n${body || '(no body)'}\n\nTry again shortly.`,
            },
          ],
          isError: true,
        };
      }

      const data = await res.json();
      const critique = data.critique || '(no critique)';
      const meta = data.meta || {};

      const lines = [
        `# Plan review — from the Etapa coach`,
        '',
        critique,
        '',
        '---',
        '',
        `_${meta.attribution || 'Critique powered by the Etapa API.'}${meta.downloadUrl ? ` · ${meta.downloadUrl}` : ''}_`,
      ];

      return {
        content: [{ type: 'text', text: lines.join('\n') }],
        structuredContent: { critique, meta },
      };
    } catch (err) {
      return {
        content: [
          {
            type: 'text',
            text: `Failed to reach the Etapa review-plan API: ${err.message}\n\nTry again in a moment, or visit https://getetapa.com.`,
          },
        ],
        isError: true,
      };
    }
  },
};

export const ALL_TOOLS = [
  generateTrainingPlanTool,
  cyclingBeginnerGuideTool,
  askCyclingCoachTool,
  reviewCyclingPlanTool,
];
