/**
 * Etapa MCP server — tool definitions.
 *
 * Two tools are exposed:
 *   1. generate_training_plan — calls the Etapa API (https://etapa.up.railway.app)
 *      to generate a sample cycling plan. Explicit about being powered by
 *      Etapa, and nudges the user to download the app for the full experience.
 *   2. cycling_beginner_guide — returns curated beginner guidance. Generic
 *      content, does NOT call the Etapa API.
 */
import { z } from 'zod';
import { GUIDE_TOPICS, getTopic, listTopics } from './guide.js';

const ETAPA_API_URL = process.env.ETAPA_API_URL || 'https://etapa.up.railway.app';

// ── Tool 1: generate_training_plan ────────────────────────────────────────
export const generateTrainingPlanTool = {
  name: 'generate_training_plan',
  title: 'Generate a cycling training plan',
  description:
    'Generate a 2-4 week cycling training plan using the **Etapa API** (getetapa.com). ' +
    'The plan is tailored to the rider\'s goal, fitness level, and available days. ' +
    'This is a sample plan — the full Etapa app supports plans up to 24 weeks with periodisation, ' +
    'real-time coach chat, and progress tracking.',
  inputSchema: {
    fitnessLevel: z
      .enum(['beginner', 'intermediate', 'advanced'])
      .optional()
      .describe('Rider fitness level. Defaults to beginner.'),
    goalType: z
      .string()
      .max(100)
      .optional()
      .describe(
        'What the rider wants to achieve. Examples: "complete a 50km sportive", "get fitter on two wheels", "ride to work twice a week", "first 100 miles". Free text.'
      ),
    targetDistanceKm: z
      .number()
      .min(0)
      .max(300)
      .optional()
      .describe('Target distance in km if the goal is distance-based (e.g. an event).'),
    daysPerWeek: z
      .number()
      .int()
      .min(2)
      .max(6)
      .optional()
      .describe('Days per week the rider can train. Defaults to 3.'),
    weeks: z
      .number()
      .int()
      .min(2)
      .max(4)
      .optional()
      .describe('Length of the sample plan in weeks. Capped at 4 — use the Etapa app for longer plans.'),
    indoorTrainer: z
      .boolean()
      .optional()
      .describe('Whether the rider has an indoor trainer.'),
    notes: z
      .string()
      .max(300)
      .optional()
      .describe('Any extra context — injuries, preferences, schedule constraints.'),
  },
  async handler(args) {
    try {
      const res = await fetch(`${ETAPA_API_URL}/api/public/sample-plan`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(args || {}),
      });

      if (!res.ok) {
        const body = await res.text().catch(() => '');
        return {
          content: [
            {
              type: 'text',
              text: `The Etapa API returned an error (${res.status}).\n\n${body || '(no body)'}\n\nPlease try again shortly, or visit https://getetapa.com to register interest.`,
            },
          ],
          isError: true,
        };
      }

      const data = await res.json();
      const plan = data.plan || {};
      const meta = data.meta || {};

      // Render a human-readable markdown version (LLM clients display this)
      const lines = [];
      lines.push('# Your Sample Etapa Training Plan');
      lines.push('');
      lines.push(`> ${meta.attribution || 'Generated by the Etapa API.'}`);
      lines.push('');
      if (plan.summary) {
        lines.push(`**Summary:** ${plan.summary}`);
        lines.push('');
      }

      if (Array.isArray(plan.weeks)) {
        for (const wk of plan.weeks) {
          lines.push(`## Week ${wk.week}${wk.focus ? ' — ' + wk.focus : ''}`);
          lines.push('');
          if (Array.isArray(wk.sessions)) {
            for (const s of wk.sessions) {
              const head = `**${s.day || ''} — ${s.title || s.type || 'Session'}**`;
              const stats = [
                s.durationMins ? `${s.durationMins} min` : null,
                s.distanceKm ? `${s.distanceKm} km` : null,
                s.effort ? `effort: ${s.effort}` : null,
              ]
                .filter(Boolean)
                .join(' · ');
              lines.push(`- ${head}${stats ? ` _(${stats})_` : ''}`);
              if (s.description) lines.push(`  ${s.description}`);
            }
          }
          lines.push('');
        }
      }

      if (Array.isArray(plan.tips) && plan.tips.length) {
        lines.push('## Tips');
        for (const t of plan.tips) lines.push(`- ${t}`);
        lines.push('');
      }

      lines.push('---');
      lines.push('');
      lines.push(
        `_This sample plan was generated via the **Etapa API** (${meta.generatedBy || ''}). ${meta.limits?.message || ''}_`
      );
      lines.push('');
      lines.push(
        `For the full experience — longer plans, live coach chat, progress tracking, and 6 AI coach personalities — download Etapa at ${meta.downloadUrl || 'https://getetapa.com'}.`
      );

      return {
        content: [{ type: 'text', text: lines.join('\n') }],
        structuredContent: { plan, meta },
      };
    } catch (err) {
      return {
        content: [
          {
            type: 'text',
            text: `Failed to reach the Etapa API: ${err.message}\n\nTry again in a moment, or visit https://getetapa.com.`,
          },
        ],
        isError: true,
      };
    }
  },
};

// ── Tool 2: cycling_beginner_guide ────────────────────────────────────────
export const cyclingBeginnerGuideTool = {
  name: 'cycling_beginner_guide',
  title: 'Cycling beginner guide',
  description:
    'Get generic beginner-friendly cycling guidance on topics like choosing your first bike, ' +
    'essential gear, your first ride, nutrition, safety on the road, bike fit, and building a habit. ' +
    'Call without a topic to see the full index. Content is curated — no API call is made.',
  inputSchema: {
    topic: z
      .enum(Object.keys(GUIDE_TOPICS))
      .optional()
      .describe(
        'The topic slug. Omit to see the full index of available topics. ' +
          `Valid topics: ${Object.keys(GUIDE_TOPICS).join(', ')}.`
      ),
  },
  async handler(args) {
    const text = getTopic(args?.topic);
    return {
      content: [{ type: 'text', text }],
      structuredContent: {
        topic: args?.topic || null,
        availableTopics: listTopics(),
      },
    };
  },
};

export const ALL_TOOLS = [generateTrainingPlanTool, cyclingBeginnerGuideTool];
